import QEC.Stabilizer.Codes.Mitten.M150.Data
import QEC.Stabilizer.Codes.Mitten.M150.Defs
import QEC.Stabilizer.Codes.Mitten.M150.StabilizerCode
import QEC.Stabilizer.Codes.Mitten.M150.Witness
import QEC.Stabilizer.Codes.Mitten.M150.FloorCore
import QEC.Stabilizer.Codes.Mitten.M150.FloorData
import QEC.Stabilizer.Codes.Mitten.M150.FloorSweepX
import QEC.Stabilizer.Codes.Mitten.M150.FloorSweepZ
import QEC.Stabilizer.Codes.Mitten.M150.FloorBridge
import QEC.Stabilizer.Codes.Mitten.M150.FloorZSide
import QEC.Stabilizer.Codes.Mitten.M150.FloorXSide
import QEC.Stabilizer.Codes.Mitten.M150.Distance

/-!
# Mitten codes

Non-abelian lifted-product qLDPC codes (Bhardwaj et al., *High-rate
qLDPC processors*, arXiv:2607.28795): LP(A,B) with 1×2 base rows of
weight-3 entries over `𝔽₂[G]`, `G` non-abelian — five qubit blocks,
rate 1/5, check weight 9.  Framework layer:
`Framework/Homological/LiftedProduct.lean`.

- `M150/` — the `[[150,30,10]]` instance over `C₅×S₃`
  (`Data` generated by
  `qec-lab:experiments/bb_lab/scripts/m150_gen_lean_data.py`; attempt
  state `qec-lab:pipeline/attempts/mitten_150_30_10/`).
-/
