/-
# The seamC ↔ δ₂ homological transport: `BocksteinVanishes` from the element form

The A13 L2 gap (`qec-lab:experiments/bb_lab/notes/A13_L2_formalization_plan.md`,
"Execution status"): the element-level Bockstein fact `δ₁∘δ₂ = 0`
(`BocksteinLift.bockstein_element_form`, discharged for order-4 deck group
algebras by `BBEpsFreeGroupAlgebra`) had not been identified with the
homological criterion `BBTransferH1.BocksteinVanishes`
(`ker τ_* ≤ range p_*` on `H₁`).  This file closes that gap.

The route avoids constructing `δ₁` and `H₀` altogether:

* `pull1_mem_boundaries_iff_seamCoset` (`BBDeficitWall`) already says
  `ker τ_*` is generated by the seam classes `[seamC ζ]`, `ζ ∈ ker ∂₂` —
  the connecting-map slot `im δ₂ = ker τ_*`.
* **The transport core** (`exists_cycle_push_eq_seamC`): for every base
  2-cycle `ζ` the seam chain `seamC ζ` is the pushforward of a *cover
  cycle* — on the nose, not just mod boundaries.  Writing `z := liftC2 ζ`
  and `ã, b̃` for the sheet-0 lifts of the two halves of `seamC ζ`, the
  transfer identity `τ₀ = ε·lift` (`pull0_eq_conv_deckPoly_liftC2`) turns
  `τ₁(seamC ζ) = liftStab ζ` (`pull1_seamC`) into `A⋆z = ε⋆ã`,
  `B⋆z = ε⋆b̃` (`ε := deckPoly = 1 + x^σ`).  The element form
  (`BocksteinElementForm`) supplies `r, s` with
  `A⋆b̃ + B⋆ã = ε⋆(A⋆r + B⋆s)`, and then
  `v := (ã + ε⋆s | b̃ + ε⋆r)` is a cover 1-cycle (char 2: the two defect
  terms cancel) with `p₁ v = seamC ζ` (the `ε`-corrections die under `p`).
* `bocksteinVanishes_of_elementForm` packages this at the `H₁` level, and
  the rank corollaries `E = k̃ − k`, `dim ker ε_* = k` follow from
  `BBTransferH1`.

The element form itself is discharged from an **order-4 lift** of the deck
(`elementForm_of_orderFourLift`): a group `Ĝ` with `σ̂` of exact order 4,
a surjection `q : Ĝ →+ G` with `q σ̂ = σ` and `ker q = {0, 2σ̂}`.  The ring
route (`bockstein_span_of_ringHom`, abstract): `ρ : 𝔽₂[Ĝ] → 𝔽₂[G]` is
surjective with kernel exactly `(ε̂²)` (computed by the repo's own
fiber-sum exactness applied to the hat cover, `liftCoverData`), so the
quotient hypotheses of `BocksteinLift.bockstein_element_form` hold with
`Ann(ε̂) = (ε̂³)` supplied by L2a
(`BBEpsFree.epsFree_one_add_single_of_addOrderOf` at `2^2`), and the span
conclusion descends along `ρ` and transports to convolution language
through `convEquiv`.

This is the paper's main-theorem bridge (A13 §1–§2): the toy free-`D`
self-dual complex has `δ₁∘δ₂ ≠ 0`, so no exactness formality can prove it —
the order-4 liftability consumed here is the mathematical content.
-/

import QEC.Stabilizer.Framework.Homological.BBTransferH1
import QEC.Stabilizer.Framework.Homological.BBDeficitWall
import QEC.Stabilizer.Framework.Homological.BBConvRing
import QEC.Stabilizer.Framework.Homological.BBEpsFreeGroupAlgebra

namespace Quantum
namespace Stabilizer
namespace Homological
namespace BB

open scoped BigOperators
open scoped Homology

-- Defeq checks through `coverComplex`/`baseComplex` projections and the
-- `liftCoverData` structure literal unfold deep `Prod`/`ZMod` instance
-- chains, exactly as in `BBCover.lean`.
set_option maxRecDepth 4096

/-! ## Chain-level utilities: halves and assembly -/

section Halves

variable {G : Type}

/-- Assemble a 1-chain from its two halves. -/
def joinHalves (vL vR : G → ZMod 2) : G × Fin 2 → ZMod 2 :=
  fun p => if p.2 = 0 then vL p.1 else vR p.1

@[simp] lemma leftHalf_joinHalves (vL vR : G → ZMod 2) :
    leftHalf (joinHalves vL vR) = vL := by
  funext g
  change (if (0 : Fin 2) = 0 then vL g else vR g) = vL g
  rw [if_pos rfl]

@[simp] lemma rightHalf_joinHalves (vL vR : G → ZMod 2) :
    rightHalf (joinHalves vL vR) = vR := by
  funext g
  change (if (1 : Fin 2) = 0 then vL g else vR g) = vR g
  rw [if_neg (by decide)]

/-- Two 1-chains with equal halves are equal. -/
lemma eq_of_halves {v w : G × Fin 2 → ZMod 2}
    (hL : leftHalf v = leftHalf w) (hR : rightHalf v = rightHalf w) :
    v = w := by
  funext p
  rcases p with ⟨g, j⟩
  fin_cases j
  · exact congrFun hL g
  · exact congrFun hR g

end Halves

section BoundaryHalves

variable {G : Type} [Fintype G] [AddCommGroup G]

/-- The left half of `∂₂ f` is `A ⋆ f`. -/
lemma leftHalf_bbBoundary2Fn (A B f : G → ZMod 2) :
    leftHalf (bbBoundary2Fn A B f) = A ⋆ f := by
  funext g
  change (if (0 : Fin 2) = 0 then (A ⋆ f) g else (B ⋆ f) g) = (A ⋆ f) g
  rw [if_pos rfl]

/-- The right half of `∂₂ f` is `B ⋆ f`. -/
lemma rightHalf_bbBoundary2Fn (A B f : G → ZMod 2) :
    rightHalf (bbBoundary2Fn A B f) = B ⋆ f := by
  funext g
  change (if (1 : Fin 2) = 0 then (A ⋆ f) g else (B ⋆ f) g) = (B ⋆ f) g
  rw [if_neg (by decide)]

end BoundaryHalves

/-- The fiber sum of the zero chain is zero. -/
lemma fiberSumFn_zero {I J : Type} [Fintype I] [DecidableEq J] (f : I → J) :
    fiberSumFn f (0 : I → ZMod 2) = 0 := by
  funext j
  simp [fiberSumFn_apply]

/-! ## The abstract ring core: the element-form span descends along a
square-zero cover of rings -/

section RingLift

/-- **The element-form span, pushed down a square-zero ring cover.**  Let
`ρ : R̂ → R` be a surjective ring map with `ker ρ ⊆ (ε̂²)`, `ρ ε̂ = ε`,
`ε² = 0`, where upstairs `char R̂ = 2` and `Ann(ε̂) = (ε̂³)`.  Then the
Bockstein element form holds downstairs: whenever `A·z = ε·a` and
`B·z = ε·b` in `R`, the representative `A·b + B·a` lies in `ε·(A, B)`,
with explicit Bezout witnesses.

This is `BocksteinLift.bockstein_element_form` transported through the
isomorphism `R ≅ R̂ ⧸ (ε̂²)` — but stated without constructing the
isomorphism: hypotheses are lifted through surjectivity of `ρ`, the
quotient conclusion is unpacked by `Ideal.mem_span_pair`, and the witness
identity descends along `ρ` (the `(ε̂²)`-ambiguity dies because
`ρ(ε̂²) = ε² = 0`). -/
theorem bockstein_span_of_ringHom {Rh Rg : Type*} [CommRing Rh] [CommRing Rg]
    (ρ : Rh →+* Rg) (εh : Rh) (εg : Rg)
    (hchar : (2 : Rh) = 0)
    (hann : ∀ w : Rh, εh * w = 0 → ∃ v, w = εh ^ 3 * v)
    (hker : ∀ x : Rh, ρ x = 0 → x ∈ Ideal.span {εh ^ 2})
    (hρε : ρ εh = εg)
    (hεg2 : εg ^ 2 = 0)
    (hsurj : Function.Surjective ⇑ρ)
    {Am Bm Z a b : Rg}
    (hAZ : Am * Z = εg * a)
    (hBZ : Bm * Z = εg * b) :
    ∃ r s : Rg, Am * b + Bm * a = εg * (Am * r + Bm * s) := by
  obtain ⟨Amh, hAmh⟩ := hsurj Am
  obtain ⟨Bmh, hBmh⟩ := hsurj Bm
  obtain ⟨Zh, hZh⟩ := hsurj Z
  obtain ⟨ah, hah⟩ := hsurj a
  obtain ⟨bh, hbh⟩ := hsurj b
  have hmk : ∀ x : Rh, ρ x = 0 →
      Ideal.Quotient.mk (Ideal.span {εh ^ 2}) x = 0 := fun x hx =>
    Ideal.Quotient.eq_zero_iff_mem.mpr (hker x hx)
  -- the two quotient-level `ε`-divisibility hypotheses
  have hQA : Ideal.Quotient.mk (Ideal.span {εh ^ 2}) Amh
        * Ideal.Quotient.mk (Ideal.span {εh ^ 2}) Zh
      = Ideal.Quotient.mk (Ideal.span {εh ^ 2}) εh
        * Ideal.Quotient.mk (Ideal.span {εh ^ 2}) ah := by
    rw [← map_mul, ← map_mul, ← sub_eq_zero, ← map_sub]
    apply hmk
    rw [map_sub, map_mul, map_mul, hAmh, hZh, hρε, hah, hAZ, sub_self]
  have hQB : Ideal.Quotient.mk (Ideal.span {εh ^ 2}) Bmh
        * Ideal.Quotient.mk (Ideal.span {εh ^ 2}) Zh
      = Ideal.Quotient.mk (Ideal.span {εh ^ 2}) εh
        * Ideal.Quotient.mk (Ideal.span {εh ^ 2}) bh := by
    rw [← map_mul, ← map_mul, ← sub_eq_zero, ← map_sub]
    apply hmk
    rw [map_sub, map_mul, map_mul, hBmh, hZh, hρε, hbh, hBZ, sub_self]
  -- the element form upstairs, in the quotient
  have hmem := BocksteinLift.bockstein_element_form εh Amh Bmh hchar hann
    (Ideal.Quotient.mk (Ideal.span {εh ^ 2}) Zh)
    (Ideal.Quotient.mk (Ideal.span {εh ^ 2}) ah)
    (Ideal.Quotient.mk (Ideal.span {εh ^ 2}) bh) hQA hQB
  obtain ⟨U, V, hUV⟩ := Ideal.mem_span_pair.mp hmem
  obtain ⟨Uh, rfl⟩ := Ideal.Quotient.mk_surjective U
  obtain ⟨Vh, rfl⟩ := Ideal.Quotient.mk_surjective V
  -- collapse the witness identity to a single `(ε̂²)`-membership
  have hzero : Ideal.Quotient.mk (Ideal.span {εh ^ 2})
      (Uh * (εh * Amh) + Vh * (εh * Bmh) - (Amh * bh + Bmh * ah)) = 0 := by
    simp only [map_sub, map_add, map_mul]
    rw [hUV]
    exact sub_self _
  obtain ⟨T, hT⟩ := Ideal.mem_span_singleton.mp
    (Ideal.Quotient.eq_zero_iff_mem.mp hzero)
  -- descend along `ρ`: the `(ε̂²)`-ambiguity maps to `ε²·ρT = 0`
  have h0 := congrArg (⇑ρ) hT
  simp only [map_sub, map_add, map_mul, map_pow] at h0
  rw [hρε, hAmh, hBmh, hah, hbh, hεg2, zero_mul] at h0
  refine ⟨ρ Uh, ρ Vh, ?_⟩
  have h1 := sub_eq_zero.mp h0
  rw [← h1]
  ring

end RingLift

/-! ## Group-algebra ↔ convolution bridges for the descent -/

section ConvBridges

/-- `convEquiv` sends `1 + x^σ` to the chain `δ₀ + δ_σ` (the shape of
`deckPoly`). -/
lemma convEquiv_one_add_single {G : Type} [Fintype G] [AddCommGroup G]
    [DecidableEq G] (σ : G) :
    convEquiv (1 + AddMonoidAlgebra.single σ (1 : ZMod 2))
      = Pi.single (0 : G) 1 + Pi.single σ 1 := by
  funext g
  rw [map_add, Pi.add_apply, Pi.add_apply, convEquiv_apply, convEquiv_apply]
  congr 1
  · rw [AddMonoidAlgebra.one_def, AddMonoidAlgebra.single_apply, Pi.single_apply]
    exact if_congr eq_comm rfl rfl
  · rw [AddMonoidAlgebra.single_apply, Pi.single_apply]
    exact if_congr eq_comm rfl rfl

/-- Under `convEquiv`, the group-algebra pushforward `mapDomain q` is the
chain-level fiber sum along `q`. -/
lemma convEquiv_mapDomainRingHom {Ghat G : Type}
    [Fintype Ghat] [AddCommGroup Ghat]
    [Fintype G] [AddCommGroup G] [DecidableEq G]
    (q : Ghat →+ G) (x : AddMonoidAlgebra (ZMod 2) Ghat) :
    convEquiv (AddMonoidAlgebra.mapDomainRingHom (ZMod 2) q x)
      = fiberSumFn (⇑q) (convEquiv x) := by
  classical
  induction x using AddMonoidAlgebra.induction_linear with
  | zero => simp only [map_zero, fiberSumFn_zero]
  | add f g hf hg => simp only [map_add, fiberSumFn_add, hf, hg]
  | single g0 c0 =>
    have hmap : AddMonoidAlgebra.mapDomainRingHom (ZMod 2) q
        (AddMonoidAlgebra.single g0 c0) = AddMonoidAlgebra.single (q g0) c0 := by
      change AddMonoidAlgebra.mapDomain (⇑q) _ = _
      exact AddMonoidAlgebra.mapDomain_single
    rw [hmap]
    funext j
    rw [convEquiv_apply, fiberSumFn_apply, Finset.sum_eq_single g0]
    · rw [convEquiv_apply, AddMonoidAlgebra.single_apply,
        AddMonoidAlgebra.single_apply, if_pos rfl]
    · intro g1 _ hne
      rw [convEquiv_apply, AddMonoidAlgebra.single_apply, if_neg (Ne.symm hne)]
      exact ite_self 0
    · intro habs
      exact absurd (Finset.mem_univ g0) habs

end ConvBridges

/-! ## The hat cover: an order-4 lift as an `XDoubleCoverData` bundle -/

section LiftCover

variable {G : Type} [Fintype G] [AddCommGroup G] [DecidableEq G]
variable {Ghat : Type} [Fintype Ghat] [AddCommGroup Ghat] [DecidableEq Ghat]

/-- The transfer bundle of an order-4 lift `q : Ĝ →+ G` with deck
`c = σ̂ + σ̂`: an `XDoubleCoverData Ĝ G` with zero polynomials.  Only its
transfer layer (`pull0`, `push0`, `liftC2`, `deckPoly`) is used — it lets
the generic level-0 identities (`pull0_eq_conv_deckPoly_liftC2`) compute
the kernel of `𝔽₂[Ĝ] → 𝔽₂[G]`. -/
noncomputable def liftCoverData (q : Ghat →+ G) (shat : Ghat)
    (hc : shat + shat ≠ 0)
    (hfiber : ∀ g g' : Ghat, q g' = q g ↔ g' = g ∨ g' = g + (shat + shat))
    (hsurj : Function.Surjective ⇑q) :
    XDoubleCoverData Ghat G where
  proj := q
  deckS := shat + shat
  sec := Function.surjInv hsurj
  Ac := 0
  Bc := 0
  Ab := 0
  Bb := 0
  deckS_ne_zero := hc
  proj_fiber := hfiber
  proj_sec := fun p => Function.surjInv_eq hsurj p
  push_A := fiberSumFn_zero ⇑q
  push_B := fiberSumFn_zero ⇑q

end LiftCover

namespace XDoubleCoverData

variable {G H : Type}
  [Fintype G] [AddCommGroup G] [DecidableEq G]
  [Fintype H] [AddCommGroup H] [DecidableEq H]
  (D : XDoubleCoverData G H)

/-! ## Level-0 transfer identities: `τ₀ = ε · lift` -/

/-- The chain identity `τ₀(p₀ w) = w + σw` on `C₀`/`C₂` chains (level-0
sibling of `pull1_push1`). -/
theorem pull0_push0 (w : G → ZMod 2) :
    D.pull0 (D.push0 w) = w + D.deckShift0 w := by
  funext g
  change fiberSumFn (⇑D.proj) w (D.proj g) = w g + w (g + D.deckS)
  exact D.push0_pair w g

/-- `p₀ ∘ τ₀ = 0` (level-0 sibling of `push1_pull1_eq_zero`). -/
theorem push0_pull0_eq_zero (u : H → ZMod 2) :
    D.push0 (D.pull0 u) = 0 := by
  change fiberSumFn (⇑D.proj) (u ∘ ⇑D.proj) = 0
  exact fiberSumFn_pullback D.deckSigma0_ne D.proj_fiber u

/-- **`τ₀ = ε · lift`**: the pullback of a base chain is `deckPoly`
convolved with its sheet-0 lift.  This is the multiplication-operator
form of the transfer, the key identity that turns `τ₁(seamC ζ) = liftStab ζ`
into the `ε`-divisibility hypotheses of the element form. -/
theorem pull0_eq_conv_deckPoly_liftC2 (u : H → ZMod 2) :
    D.pull0 u = D.deckPoly ⋆ D.liftC2 u := by
  have h1 : D.push0 (D.liftC2 u) = u := by
    change fiberSumFn (⇑D.proj) (D.liftC2 u) = u
    exact D.push0_liftC2 u
  rw [D.conv_deckPoly_eq, ← D.pull0_push0, h1]

/-- Multiplication by `deckPoly` lands in `ker p₀`. -/
theorem push0_conv_deckPoly_eq_zero (w : G → ZMod 2) :
    D.push0 (D.deckPoly ⋆ w) = 0 := by
  rw [D.conv_deckPoly_eq, ← D.pull0_push0]
  exact D.push0_pull0_eq_zero _

/-! ## Componentwise transfer -/

/-- `p₁` acts on the left half as `p₀`. -/
lemma leftHalf_push1 (v : G × Fin 2 → ZMod 2) :
    leftHalf (D.push1 v) = D.push0 (leftHalf v) := by
  change leftHalf (fiberSumFn (Prod.map (⇑D.proj) id) v)
    = fiberSumFn (⇑D.proj) (leftHalf v)
  exact leftHalf_fiberSumFn_prodMap D.proj v

/-- `p₁` acts on the right half as `p₀`. -/
lemma rightHalf_push1 (v : G × Fin 2 → ZMod 2) :
    rightHalf (D.push1 v) = D.push0 (rightHalf v) := by
  change rightHalf (fiberSumFn (Prod.map (⇑D.proj) id) v)
    = fiberSumFn (⇑D.proj) (rightHalf v)
  exact rightHalf_fiberSumFn_prodMap D.proj v

/-- `τ₁` acts on the left half as `τ₀`. -/
lemma leftHalf_pull1 (u : H × Fin 2 → ZMod 2) :
    leftHalf (D.pull1 u) = D.pull0 (leftHalf u) := rfl

/-- `τ₁` acts on the right half as `τ₀`. -/
lemma rightHalf_pull1 (u : H × Fin 2 → ZMod 2) :
    rightHalf (D.pull1 u) = D.pull0 (rightHalf u) := rfl

/-! ## The seam chain as an `ε`-division: the element-form hypotheses -/

/-- `A⋆(lift ζ) = ε⋆(lift of the left half of seamC ζ)`: the left
component of `τ₁(seamC ζ) = liftStab ζ` read through `τ₀ = ε·lift`. -/
theorem conv_Ac_liftC2_seamC {ζ : H → ZMod 2}
    (hζ : bbBoundary2Fn D.Ab D.Bb ζ = 0) :
    D.Ac ⋆ D.liftC2 ζ
      = D.deckPoly ⋆ D.liftC2 (leftHalf (D.seamC ζ)) := by
  have hL := congrArg leftHalf (D.pull1_seamC hζ)
  rw [D.leftHalf_pull1, D.pull0_eq_conv_deckPoly_liftC2] at hL
  have hstab : leftHalf (D.liftStab ζ) = D.Ac ⋆ D.liftC2 ζ :=
    leftHalf_bbBoundary2Fn D.Ac D.Bc (D.liftC2 ζ)
  rw [hstab] at hL
  exact hL.symm

/-- `B⋆(lift ζ) = ε⋆(lift of the right half of seamC ζ)`. -/
theorem conv_Bc_liftC2_seamC {ζ : H → ZMod 2}
    (hζ : bbBoundary2Fn D.Ab D.Bb ζ = 0) :
    D.Bc ⋆ D.liftC2 ζ
      = D.deckPoly ⋆ D.liftC2 (rightHalf (D.seamC ζ)) := by
  have hR := congrArg rightHalf (D.pull1_seamC hζ)
  rw [D.rightHalf_pull1, D.pull0_eq_conv_deckPoly_liftC2] at hR
  have hstab : rightHalf (D.liftStab ζ) = D.Bc ⋆ D.liftC2 ζ :=
    rightHalf_bbBoundary2Fn D.Ac D.Bc (D.liftC2 ζ)
  rw [hstab] at hR
  exact hR.symm

/-! ## The Bockstein element form and the transport core -/

/-- **The Bockstein element form** for a cover bundle, in convolution
language: whenever `A⋆z` and `B⋆z` are `ε`-divisible (`ε = deckPoly =
1 + x^σ`), the representative `A⋆b + B⋆a` built from the `ε`-quotients
lies in `ε·(A, B)`.  This is the `δ₁∘δ₂ = 0` element fact (A13 §1, claim 4);
`elementForm_of_orderFourLift` discharges it from an order-4 lift of the
deck. -/
def BocksteinElementForm : Prop :=
  ∀ z a b : G → ZMod 2,
    D.Ac ⋆ z = D.deckPoly ⋆ a →
    D.Bc ⋆ z = D.deckPoly ⋆ b →
    ∃ r s : G → ZMod 2,
      D.Ac ⋆ b + D.Bc ⋆ a
        = D.deckPoly ⋆ (D.Ac ⋆ r + D.Bc ⋆ s)

/-- **The transport core**: under the element form, every seam chain is
the pushforward of a cover 1-cycle — on the nose.  The corrected lift
`v = (ã + ε⋆s | b̃ + ε⋆r)` is a cycle because the element form makes the
two boundary defects cancel in characteristic 2, and pushes to `seamC ζ`
because `p₀` kills `ε`-multiples. -/
theorem exists_cycle_push_eq_seamC (hEF : D.BocksteinElementForm)
    {ζ : H → ZMod 2} (hζ : bbBoundary2Fn D.Ab D.Bb ζ = 0) :
    ∃ v : G × Fin 2 → ZMod 2,
      v ∈ D.coverComplex.cycles ∧ D.push1 v = D.seamC ζ := by
  set za := D.liftC2 (leftHalf (D.seamC ζ)) with hza
  set zb := D.liftC2 (rightHalf (D.seamC ζ)) with hzb
  have hA : D.Ac ⋆ D.liftC2 ζ = D.deckPoly ⋆ za :=
    D.conv_Ac_liftC2_seamC hζ
  have hB : D.Bc ⋆ D.liftC2 ζ = D.deckPoly ⋆ zb :=
    D.conv_Bc_liftC2_seamC hζ
  obtain ⟨r, s, hrs⟩ := hEF (D.liftC2 ζ) za zb hA hB
  refine ⟨joinHalves (za + D.deckPoly ⋆ s) (zb + D.deckPoly ⋆ r),
    ?_, ?_⟩
  · -- the corrected lift is a cover cycle
    have hcommA : D.Ac ⋆ (D.deckPoly ⋆ r)
        = D.deckPoly ⋆ (D.Ac ⋆ r) := by
      rw [← conv_assoc, conv_comm D.Ac D.deckPoly, conv_assoc]
    have hcommB : D.Bc ⋆ (D.deckPoly ⋆ s)
        = D.deckPoly ⋆ (D.Bc ⋆ s) := by
      rw [← conv_assoc, conv_comm D.Bc D.deckPoly, conv_assoc]
    have hbd : bbBoundary1Fn D.Ac D.Bc
        (joinHalves (za + D.deckPoly ⋆ s) (zb + D.deckPoly ⋆ r)) = 0 := by
      have hexp : bbBoundary1Fn D.Ac D.Bc
          (joinHalves (za + D.deckPoly ⋆ s) (zb + D.deckPoly ⋆ r))
          = D.Bc ⋆ leftHalf (joinHalves (za + D.deckPoly ⋆ s)
              (zb + D.deckPoly ⋆ r))
            + D.Ac ⋆ rightHalf (joinHalves (za + D.deckPoly ⋆ s)
              (zb + D.deckPoly ⋆ r)) := rfl
      rw [hexp, leftHalf_joinHalves, rightHalf_joinHalves, conv_add_right,
        conv_add_right, hcommA, hcommB]
      have hre : D.Bc ⋆ za + D.deckPoly ⋆ (D.Bc ⋆ s)
          + (D.Ac ⋆ zb + D.deckPoly ⋆ (D.Ac ⋆ r))
          = (D.Ac ⋆ zb + D.Bc ⋆ za)
            + D.deckPoly ⋆ (D.Ac ⋆ r + D.Bc ⋆ s) := by
        rw [conv_add_right]
        abel
      rw [hre, hrs]
      funext g
      exact CharTwo.add_self_eq_zero _
    have hgoal : D.coverComplex.boundary1
        (joinHalves (za + D.deckPoly ⋆ s) (zb + D.deckPoly ⋆ r)) = 0 :=
      hbd
    exact hgoal
  · -- it pushes forward to the seam chain exactly
    apply eq_of_halves
    · rw [D.leftHalf_push1, leftHalf_joinHalves, map_add,
        D.push0_conv_deckPoly_eq_zero, add_zero, hza]
      change fiberSumFn (⇑D.proj) (D.liftC2 (leftHalf (D.seamC ζ)))
        = leftHalf (D.seamC ζ)
      exact D.push0_liftC2 _
    · rw [D.rightHalf_push1, rightHalf_joinHalves, map_add,
        D.push0_conv_deckPoly_eq_zero, add_zero, hzb]
      change fiberSumFn (⇑D.proj) (D.liftC2 (rightHalf (D.seamC ζ)))
        = rightHalf (D.seamC ζ)
      exact D.push0_liftC2 _

/-! ## The capstone: `BocksteinVanishes` from the element form -/

/-- **The seamC ↔ δ₂ transport**: the element form implies the
Bockstein-vanishing criterion `ker τ_* ≤ range p_*` on `H₁`.  Unpack
`ker τ_*` through the seam-coset characterization (`im δ₂ = ker τ₁`,
`BBDeficitWall.pull1_mem_boundaries_iff_seamCoset`), then push the
transport-core cycle forward. -/
theorem bocksteinVanishes_of_elementForm (hEF : D.BocksteinElementForm) :
    D.BocksteinVanishes := by
  intro x hx
  obtain ⟨⟨u, hu⟩, rfl⟩ := Submodule.Quotient.mk_surjective _ x
  have hx0 : D.pullH1 (Submodule.Quotient.mk ⟨u, hu⟩) = 0 :=
    LinearMap.mem_ker.mp hx
  rw [D.pullH1_mk, Submodule.Quotient.mk_eq_zero] at hx0
  have hbd : D.pull1 u ∈ D.coverComplex.boundaries := hx0
  obtain ⟨ζ, hζ, f, hueq⟩ := (D.pull1_mem_boundaries_iff_seamCoset u).mp hbd
  obtain ⟨v, hvcyc, hvpush⟩ := D.exists_cycle_push_eq_seamC hEF hζ
  refine ⟨Submodule.Quotient.mk ⟨v, hvcyc⟩, ?_⟩
  rw [D.pushH1_mk, Submodule.Quotient.eq]
  change ((D.push1Cycles ⟨v, hvcyc⟩ - ⟨u, hu⟩ : D.baseComplex.cycles) :
      D.baseComplex.C1 → ZMod 2) ∈ D.baseComplex.boundaries
  refine ⟨f, funext fun p => ?_⟩
  have hp : u p = D.seamC ζ p + bbBoundary2Fn D.Ab D.Bb f p := by
    have h := congrFun hueq p
    rwa [Pi.add_apply] at h
  have hv : D.push1 v p = D.seamC ζ p := congrFun hvpush p
  have key : ∀ a b c d : ZMod 2, a = b + c → d = b → c = d - a := by decide
  exact key (u p) (D.seamC ζ p) (bbBoundary2Fn D.Ab D.Bb f p)
    (D.push1 v p) hp hv

/-! ## Rank corollaries under the element form -/

/-- **The Bockstein rank equality** under the element form:
`dim (1+σ)·H₁(cover) = k̃ − k`. -/
theorem finrank_range_epsH1_eq_of_elementForm (hEF : D.BocksteinElementForm) :
    dim₂ (LinearMap.range D.epsH1)
      = dim₂ D.coverComplex.H1
        - dim₂ D.baseComplex.H1 :=
  D.finrank_range_epsH1_eq (D.bocksteinVanishes_of_elementForm hEF)

/-- Additive form: `E + k = k̃` (in particular `k̃ ≥ k`). -/
theorem finrank_range_epsH1_add_eq_of_elementForm
    (hEF : D.BocksteinElementForm) :
    dim₂ (LinearMap.range D.epsH1)
        + dim₂ D.baseComplex.H1
      = dim₂ D.coverComplex.H1 :=
  D.finrank_range_epsH1_add_eq (D.bocksteinVanishes_of_elementForm hEF)

/-- Companion rank: `dim ker ε_* = k`. -/
theorem finrank_ker_epsH1_eq_of_elementForm (hEF : D.BocksteinElementForm) :
    dim₂ (LinearMap.ker D.epsH1)
      = dim₂ D.baseComplex.H1 :=
  D.finrank_ker_epsH1_eq (D.bocksteinVanishes_of_elementForm hEF)

/-! ## Discharging the element form from an order-4 lift of the deck -/

section OrderFourLift

/-- **The element form from an order-4 lift.**  If the deck `σ = deckS`
lifts one rung up the doubling tower — a group `Ĝ` with `σ̂` of exact
order 4 and a surjection `q : Ĝ →+ G` with `q σ̂ = σ` and
`ker q = {0, σ̂ + σ̂}` — then `BocksteinElementForm` holds.

Route: `ρ = 𝔽₂[q] : 𝔽₂[Ĝ] → 𝔽₂[G]` is surjective with `ker ρ ⊆ (ε̂²)`
(fiber-sum exactness of the hat cover `liftCoverData`, read through
`convEquiv`), `Ann(ε̂) = (ε̂³)` holds by L2a
(`epsFree_one_add_single_of_addOrderOf` at order `2² = 4`), and
`bockstein_span_of_ringHom` descends the element form along `ρ`;
`convEquiv` transports the result to convolution language. -/
theorem elementForm_of_orderFourLift {Ghat : Type}
    [Finite Ghat] [AddCommGroup Ghat]
    (q : Ghat →+ G) (shat : Ghat)
    (horder : addOrderOf shat = 4)
    (hsurj : Function.Surjective ⇑q)
    (hshat : q shat = D.deckS)
    (hker : ∀ x : Ghat, q x = 0 ↔ x = 0 ∨ x = shat + shat) :
    D.BocksteinElementForm := by
  classical
  letI : Fintype Ghat := Fintype.ofFinite Ghat
  intro z a b hAz hBz
  -- ### group facts for the hat cover
  have hc : shat + shat ≠ 0 := by
    intro hcon
    have h2s : (2 : ℕ) • shat = 0 := by rw [two_nsmul]; exact hcon
    have hdvd := addOrderOf_dvd_iff_nsmul_eq_zero.mpr h2s
    rw [horder] at hdvd
    have hle := Nat.le_of_dvd (by norm_num) hdvd
    omega
  have hfiber : ∀ g g' : Ghat, q g' = q g ↔ g' = g ∨ g' = g + (shat + shat) := by
    intro g g'
    constructor
    · intro h
      have h0 : q (g' - g) = 0 := by rw [map_sub, h, sub_self]
      rcases (hker _).mp h0 with h1 | h1
      · exact Or.inl (sub_eq_zero.mp h1)
      · refine Or.inr ?_
        rw [sub_eq_iff_eq_add] at h1
        rw [h1]
        exact add_comm _ _
    · rintro (rfl | rfl)
      · rfl
      · rw [map_add, map_add, hshat, D.deckS_add_deckS, add_zero]
  set Dh := liftCoverData q shat hc hfiber hsurj with hDh
  -- ### characteristic-2 facts
  have h2 : (2 : ZMod 2) = 0 := by decide
  have h2hat : (2 : AddMonoidAlgebra (ZMod 2) Ghat) = 0 := by
    rw [← map_ofNat (algebraMap (ZMod 2) (AddMonoidAlgebra (ZMod 2) Ghat)) 2,
      h2, map_zero]
  have h2G : (2 : AddMonoidAlgebra (ZMod 2) G) = 0 := by
    rw [← map_ofNat (algebraMap (ZMod 2) (AddMonoidAlgebra (ZMod 2) G)) 2,
      h2, map_zero]
  -- ### `Ann(ε̂) = (ε̂³)` from L2a (order-4 `EpsFree`)
  have hEF4 : BBDeckTower.EpsFree
      (1 + AddMonoidAlgebra.single shat (1 : ZMod 2)) 4 := by
    have h := BBEpsFree.epsFree_one_add_single_of_addOrderOf h2 shat 2
      (horder.trans (by norm_num))
    norm_num at h
    exact h
  have hann := BBEpsFree.hann_of_epsFree hEF4
  -- ### `ε̂²` and `ε²` in single form
  have hsq : (1 + AddMonoidAlgebra.single shat (1 : ZMod 2)) ^ 2
      = 1 + AddMonoidAlgebra.single (shat + shat) (1 : ZMod 2) := by
    have hpow : (AddMonoidAlgebra.single shat (1 : ZMod 2)) ^ 2
        = AddMonoidAlgebra.single (shat + shat) (1 : ZMod 2) := by
      rw [BBEpsFree.single_pow_one, two_nsmul]
    rw [add_sq, one_pow, mul_one, h2hat, zero_mul, add_zero, hpow]
  have hεGsq : (1 + AddMonoidAlgebra.single D.deckS (1 : ZMod 2)) ^ 2 = 0 := by
    have hpow : (AddMonoidAlgebra.single D.deckS (1 : ZMod 2)) ^ 2
        = AddMonoidAlgebra.single (D.deckS + D.deckS) (1 : ZMod 2) := by
      rw [BBEpsFree.single_pow_one, two_nsmul]
    rw [add_sq, one_pow, mul_one, h2G, zero_mul, add_zero, hpow,
      D.deckS_add_deckS, ← AddMonoidAlgebra.one_def, one_add_one_eq_two]
    exact h2G
  -- ### `ρ` and its interface facts
  have hρsurj : Function.Surjective
      ⇑(AddMonoidAlgebra.mapDomainRingHom (ZMod 2) q) :=
    Finsupp.mapDomain_surjective hsurj
  have hρε : AddMonoidAlgebra.mapDomainRingHom (ZMod 2) q
      (1 + AddMonoidAlgebra.single shat (1 : ZMod 2))
      = 1 + AddMonoidAlgebra.single D.deckS (1 : ZMod 2) := by
    rw [map_add, map_one]
    congr 1
    have hone : AddMonoidAlgebra.mapDomainRingHom (ZMod 2) q
        (AddMonoidAlgebra.single shat (1 : ZMod 2))
        = AddMonoidAlgebra.single (q shat) (1 : ZMod 2) := by
      change AddMonoidAlgebra.mapDomain (⇑q) _ = _
      exact AddMonoidAlgebra.mapDomain_single
    rw [hone, hshat]
  -- ### the kernel bound `ker ρ ⊆ (ε̂²)` via the hat-cover exactness
  have hkerspan : ∀ x : AddMonoidAlgebra (ZMod 2) Ghat,
      AddMonoidAlgebra.mapDomainRingHom (ZMod 2) q x = 0 →
      x ∈ Ideal.span {(1 + AddMonoidAlgebra.single shat (1 : ZMod 2)) ^ 2} := by
    intro x hx
    have hσne : ∀ g : Ghat, g + (shat + shat) ≠ g := by
      intro g hcon
      apply hc
      have h' : g + (shat + shat) = g + 0 := by rw [add_zero]; exact hcon
      exact add_left_cancel h'
    have hfx : fiberSumFn (⇑q) (convEquiv x) = 0 := by
      rw [← convEquiv_mapDomainRingHom q x, hx, map_zero]
    obtain ⟨u, hu⟩ := (fiberSumFn_eq_zero_iff hσne hfiber
      (fun p => Function.surjInv_eq hsurj p) (convEquiv x)).mp hfx
    have hpull : convEquiv x = Dh.deckPoly ⋆ Dh.liftC2 u := by
      rw [hu, ← Dh.pull0_eq_conv_deckPoly_liftC2 u]
      rfl
    have hconvsq : convEquiv
        ((1 + AddMonoidAlgebra.single shat (1 : ZMod 2)) ^ 2)
        = Dh.deckPoly := by
      rw [hsq, convEquiv_one_add_single]
      rfl
    have hx_eq : x = (1 + AddMonoidAlgebra.single shat (1 : ZMod 2)) ^ 2
        * convEquiv.symm (Dh.liftC2 u) := by
      apply convEquiv.injective
      rw [convEquiv_mul, hconvsq, LinearEquiv.apply_symm_apply]
      exact hpull
    rw [hx_eq]
    exact Ideal.mem_span_singleton.mpr (dvd_mul_right _ _)
  -- ### transport the hypotheses into the group algebra
  have hconvεG : convEquiv (1 + AddMonoidAlgebra.single D.deckS (1 : ZMod 2))
      = D.deckPoly :=
    convEquiv_one_add_single D.deckS
  have hAZ : convEquiv.symm D.Ac * convEquiv.symm z
      = (1 + AddMonoidAlgebra.single D.deckS (1 : ZMod 2))
        * convEquiv.symm a := by
    apply convEquiv.injective
    rw [convEquiv_mul, convEquiv_mul, LinearEquiv.apply_symm_apply,
      LinearEquiv.apply_symm_apply, LinearEquiv.apply_symm_apply, hconvεG]
    exact hAz
  have hBZ : convEquiv.symm D.Bc * convEquiv.symm z
      = (1 + AddMonoidAlgebra.single D.deckS (1 : ZMod 2))
        * convEquiv.symm b := by
    apply convEquiv.injective
    rw [convEquiv_mul, convEquiv_mul, LinearEquiv.apply_symm_apply,
      LinearEquiv.apply_symm_apply, LinearEquiv.apply_symm_apply, hconvεG]
    exact hBz
  -- ### the abstract ring core
  obtain ⟨r', s', hrs'⟩ := bockstein_span_of_ringHom
    (AddMonoidAlgebra.mapDomainRingHom (ZMod 2) q)
    (1 + AddMonoidAlgebra.single shat (1 : ZMod 2))
    (1 + AddMonoidAlgebra.single D.deckS (1 : ZMod 2))
    h2hat hann hkerspan hρε hεGsq hρsurj hAZ hBZ
  -- ### back to convolution language
  refine ⟨convEquiv r', convEquiv s', ?_⟩
  have hL : convEquiv (convEquiv.symm D.Ac * convEquiv.symm b
      + convEquiv.symm D.Bc * convEquiv.symm a)
      = D.Ac ⋆ b + D.Bc ⋆ a := by
    rw [map_add, convEquiv_mul, convEquiv_mul, LinearEquiv.apply_symm_apply,
      LinearEquiv.apply_symm_apply, LinearEquiv.apply_symm_apply,
      LinearEquiv.apply_symm_apply]
  have hR : convEquiv ((1 + AddMonoidAlgebra.single D.deckS (1 : ZMod 2))
      * (convEquiv.symm D.Ac * r' + convEquiv.symm D.Bc * s'))
      = D.deckPoly ⋆ (D.Ac ⋆ convEquiv r' + D.Bc ⋆ convEquiv s') := by
    rw [convEquiv_mul, hconvεG]
    congr 1
    rw [map_add, convEquiv_mul, convEquiv_mul, LinearEquiv.apply_symm_apply,
      LinearEquiv.apply_symm_apply]
  rw [← hL, ← hR, hrs']

/-- **`BocksteinVanishes` from an order-4 lift of the deck** — the
seamC ↔ δ₂ transport composed with the element-form discharge. -/
theorem bocksteinVanishes_of_orderFourLift {Ghat : Type}
    [Finite Ghat] [AddCommGroup Ghat]
    (q : Ghat →+ G) (shat : Ghat)
    (horder : addOrderOf shat = 4)
    (hsurj : Function.Surjective ⇑q)
    (hshat : q shat = D.deckS)
    (hker : ∀ x : Ghat, q x = 0 ↔ x = 0 ∨ x = shat + shat) :
    D.BocksteinVanishes :=
  D.bocksteinVanishes_of_elementForm
    (D.elementForm_of_orderFourLift q shat horder hsurj hshat hker)

/-- **The Bockstein rank equality from an order-4 lift**:
`dim (1+σ)·H₁(cover) = k̃ − k` (A13 Theorem, claim 2). -/
theorem finrank_range_epsH1_eq_of_orderFourLift {Ghat : Type}
    [Finite Ghat] [AddCommGroup Ghat]
    (q : Ghat →+ G) (shat : Ghat)
    (horder : addOrderOf shat = 4)
    (hsurj : Function.Surjective ⇑q)
    (hshat : q shat = D.deckS)
    (hker : ∀ x : Ghat, q x = 0 ↔ x = 0 ∨ x = shat + shat) :
    dim₂ (LinearMap.range D.epsH1)
      = dim₂ D.coverComplex.H1
        - dim₂ D.baseComplex.H1 :=
  D.finrank_range_epsH1_eq
    (D.bocksteinVanishes_of_orderFourLift q shat horder hsurj hshat hker)

end OrderFourLift

end XDoubleCoverData

/-! ## The concrete order-4 lift for doubled-axis `ZMod` products -/

/-- If `4 • a = 0` and `2 • a ≠ 0` then `a` has additive order exactly 4. -/
lemma addOrderOf_eq_four_of_nsmul {A : Type*} [AddMonoid A] {a : A}
    (h4 : (4 : ℕ) • a = 0) (h2 : (2 : ℕ) • a ≠ 0) : addOrderOf a = 4 := by
  have hdvd : addOrderOf a ∣ 4 := addOrderOf_dvd_iff_nsmul_eq_zero.mpr h4
  have hnd : ¬ addOrderOf a ∣ 2 := fun hd =>
    h2 (addOrderOf_dvd_iff_nsmul_eq_zero.mp hd)
  have hle : addOrderOf a ≤ 4 := Nat.le_of_dvd (by norm_num) hdvd
  have hpos : 0 < addOrderOf a := Nat.pos_of_dvd_of_pos hdvd (by norm_num)
  set d := addOrderOf a with hd
  interval_cases d
  · exact absurd (one_dvd 2) hnd
  · exact absurd dvd_rfl hnd
  · exact absurd hdvd (by norm_num)
  · rfl

namespace XDoubleCoverData

variable {H : Type} [Fintype H] [AddCommGroup H] [DecidableEq H]

/-- **The element form for doubled-axis `ZMod` products** — the concrete
order-4 lift.  For a cover group `ZMod (2n) × ZMod m` whose deck is
`(n, t)` (the standard doubled-axis deck; `t` any order-2 twist, `0`
included), the Frattini lift `ZMod (4n) × ZMod m` with `σ̂ = (n, t)` and
`q = cast × id` discharges `BocksteinElementForm` unconditionally: `σ̂`
has exact order 4 (`2σ̂ = (2n, 0) ≠ 0` in `ZMod (4n)`), `q` is surjective
with kernel `{0, 2σ̂}` (the two multiples of `2n` below `4n`).  Every
free-ℤ₂ BB doubling cover in the program has this shape. -/
theorem elementForm_of_zmod_double {n m : ℕ} [NeZero n] [NeZero m]
    (D : XDoubleCoverData (ZMod (2 * n) × ZMod m) H)
    (t : ZMod m) (ht : t + t = 0)
    (hdeck : D.deckS = (((n : ℕ) : ZMod (2 * n)), t)) :
    D.BocksteinElementForm := by
  have hn := Nat.pos_of_ne_zero (NeZero.ne n)
  have hdvd : (2 * n) ∣ (4 * n) := ⟨2, by ring⟩
  refine D.elementForm_of_orderFourLift
    (AddMonoidHom.prodMap (ZMod.castHom hdvd (ZMod (2 * n))).toAddMonoidHom
      (AddMonoidHom.id (ZMod m)))
    (((n : ℕ) : ZMod (4 * n)), t) ?_ ?_ ?_ ?_
  · -- exact order 4
    apply addOrderOf_eq_four_of_nsmul
    · have h1 : (4 : ℕ) • ((n : ℕ) : ZMod (4 * n)) = 0 := by
        rw [nsmul_eq_mul, ← Nat.cast_mul]
        exact ZMod.natCast_self (4 * n)
      have h2 : (4 : ℕ) • t = 0 := by
        have h22 : (2 : ℕ) • t = 0 := by rw [two_nsmul]; exact ht
        rw [show (4 : ℕ) = 2 * 2 by norm_num, mul_nsmul, h22, smul_zero]
      rw [Prod.smul_mk, h1, h2]
      rfl
    · intro hcon
      rw [Prod.smul_mk] at hcon
      have h1 : (2 : ℕ) • ((n : ℕ) : ZMod (4 * n)) = 0 := by
        have h := congrArg Prod.fst hcon
        simpa using h
      rw [nsmul_eq_mul, ← Nat.cast_mul, ZMod.natCast_eq_zero_iff] at h1
      have hle := Nat.le_of_dvd (by omega) h1
      omega
  · -- surjectivity
    rw [AddMonoidHom.coe_prodMap]
    exact Function.Surjective.prodMap (ZMod.castHom_surjective hdvd)
      Function.surjective_id
  · -- maps to the deck
    rw [hdeck]
    have happ : (AddMonoidHom.prodMap
        (ZMod.castHom hdvd (ZMod (2 * n))).toAddMonoidHom
        (AddMonoidHom.id (ZMod m))) (((n : ℕ) : ZMod (4 * n)), t)
        = ((ZMod.castHom hdvd (ZMod (2 * n))) ((n : ℕ) : ZMod (4 * n)), t) :=
      rfl
    rw [happ, map_natCast]
  · -- kernel = {0, σ̂ + σ̂}
    intro x
    obtain ⟨x₁, x₂⟩ := x
    have happ : (AddMonoidHom.prodMap
        (ZMod.castHom hdvd (ZMod (2 * n))).toAddMonoidHom
        (AddMonoidHom.id (ZMod m))) (x₁, x₂)
        = ((ZMod.castHom hdvd (ZMod (2 * n))) x₁, x₂) := rfl
    have hσσ : ((((n : ℕ) : ZMod (4 * n)), t) + (((n : ℕ) : ZMod (4 * n)), t))
        = (((2 * n : ℕ) : ZMod (4 * n)), (0 : ZMod m)) := by
      rw [Prod.mk_add_mk, ht, ← Nat.cast_add, show n + n = 2 * n by ring]
    rw [happ, hσσ]
    have hval : ((x₁.val : ℕ) : ZMod (4 * n)) = x₁ := by
      rw [ZMod.natCast_val, ZMod.cast_id]
    constructor
    · intro h0
      have h1 : (ZMod.castHom hdvd (ZMod (2 * n))) x₁ = 0 :=
        (Prod.mk_eq_zero.mp h0).1
      have h2 : x₂ = 0 := (Prod.mk_eq_zero.mp h0).2
      have hcast : (ZMod.castHom hdvd (ZMod (2 * n))) x₁
          = ((x₁.val : ℕ) : ZMod (2 * n)) := by
        conv_lhs => rw [← hval]
        rw [map_natCast]
      rw [hcast, ZMod.natCast_eq_zero_iff] at h1
      have hlt : x₁.val < 4 * n := ZMod.val_lt x₁
      obtain ⟨c, hc⟩ := h1
      have hc2 : c < 2 := by
        have h4 : 2 * n * c < 2 * n * 2 := by
          calc 2 * n * c = x₁.val := hc.symm
            _ < 4 * n := hlt
            _ = 2 * n * 2 := by ring
        exact Nat.lt_of_mul_lt_mul_left h4
      interval_cases c
      · left
        have hx1 : x₁ = 0 := by
          rw [← hval, hc, mul_zero, Nat.cast_zero]
        rw [hx1, h2]
        rfl
      · right
        have hx1 : x₁ = ((2 * n : ℕ) : ZMod (4 * n)) := by
          rw [← hval, hc, mul_one]
        rw [hx1, h2]
    · rintro (h0 | h0)
      · have h1 : x₁ = 0 := (Prod.mk_eq_zero.mp h0).1
        have h2 : x₂ = 0 := (Prod.mk_eq_zero.mp h0).2
        rw [h1, h2, map_zero]
        rfl
      · have h1 : x₁ = ((2 * n : ℕ) : ZMod (4 * n)) := (Prod.ext_iff.mp h0).1
        have h2 : x₂ = 0 := (Prod.ext_iff.mp h0).2
        rw [h1, h2, map_natCast, ZMod.natCast_self]
        rfl

/-- **`BocksteinVanishes` for doubled-axis `ZMod` products** —
unconditional over the concrete BB doubling family. -/
theorem bocksteinVanishes_of_zmod_double {n m : ℕ} [NeZero n] [NeZero m]
    (D : XDoubleCoverData (ZMod (2 * n) × ZMod m) H)
    (t : ZMod m) (ht : t + t = 0)
    (hdeck : D.deckS = (((n : ℕ) : ZMod (2 * n)), t)) :
    D.BocksteinVanishes :=
  D.bocksteinVanishes_of_elementForm (D.elementForm_of_zmod_double t ht hdeck)

/-- **The Bockstein rank equality for doubled-axis `ZMod` products**:
`dim (1+σ)·H₁(cover) = k̃ − k`, unconditionally (A13 Theorem, claim 2,
for every free-ℤ₂ BB doubling cover of the program). -/
theorem finrank_range_epsH1_eq_of_zmod_double {n m : ℕ} [NeZero n] [NeZero m]
    (D : XDoubleCoverData (ZMod (2 * n) × ZMod m) H)
    (t : ZMod m) (ht : t + t = 0)
    (hdeck : D.deckS = (((n : ℕ) : ZMod (2 * n)), t)) :
    dim₂ (LinearMap.range D.epsH1)
      = dim₂ D.coverComplex.H1
        - dim₂ D.baseComplex.H1 :=
  D.finrank_range_epsH1_eq (D.bocksteinVanishes_of_zmod_double t ht hdeck)

/-- **The element form for doubled-axis `ZMod` products, second-axis
mirror** — the concrete order-4 lift with the doubled factor in the
*second* coordinate (the y-deck orientation, e.g. A19-type y-deck
covers).  For a cover group `ZMod m × ZMod (2n)` whose deck is `(t, n)`
(`t` any order-2 twist, `0` included), the Frattini lift
`ZMod m × ZMod (4n)` with `σ̂ = (t, n)` and `q = id × cast` discharges
`BocksteinElementForm` unconditionally.  Mirror of
`elementForm_of_zmod_double`. -/
theorem elementForm_of_zmod_double_right {n m : ℕ} [NeZero n] [NeZero m]
    (D : XDoubleCoverData (ZMod m × ZMod (2 * n)) H)
    (t : ZMod m) (ht : t + t = 0)
    (hdeck : D.deckS = (t, ((n : ℕ) : ZMod (2 * n)))) :
    D.BocksteinElementForm := by
  have hn := Nat.pos_of_ne_zero (NeZero.ne n)
  have hdvd : (2 * n) ∣ (4 * n) := ⟨2, by ring⟩
  refine D.elementForm_of_orderFourLift
    (AddMonoidHom.prodMap (AddMonoidHom.id (ZMod m))
      (ZMod.castHom hdvd (ZMod (2 * n))).toAddMonoidHom)
    (t, ((n : ℕ) : ZMod (4 * n))) ?_ ?_ ?_ ?_
  · -- exact order 4
    apply addOrderOf_eq_four_of_nsmul
    · have h1 : (4 : ℕ) • ((n : ℕ) : ZMod (4 * n)) = 0 := by
        rw [nsmul_eq_mul, ← Nat.cast_mul]
        exact ZMod.natCast_self (4 * n)
      have h2 : (4 : ℕ) • t = 0 := by
        have h22 : (2 : ℕ) • t = 0 := by rw [two_nsmul]; exact ht
        rw [show (4 : ℕ) = 2 * 2 by norm_num, mul_nsmul, h22, smul_zero]
      rw [Prod.smul_mk, h1, h2]
      rfl
    · intro hcon
      rw [Prod.smul_mk] at hcon
      have h1 : (2 : ℕ) • ((n : ℕ) : ZMod (4 * n)) = 0 := by
        have h := congrArg Prod.snd hcon
        simpa using h
      rw [nsmul_eq_mul, ← Nat.cast_mul, ZMod.natCast_eq_zero_iff] at h1
      have hle := Nat.le_of_dvd (by omega) h1
      omega
  · -- surjectivity
    rw [AddMonoidHom.coe_prodMap]
    exact Function.Surjective.prodMap Function.surjective_id
      (ZMod.castHom_surjective hdvd)
  · -- maps to the deck
    rw [hdeck]
    have happ : (AddMonoidHom.prodMap (AddMonoidHom.id (ZMod m))
        (ZMod.castHom hdvd (ZMod (2 * n))).toAddMonoidHom)
        (t, ((n : ℕ) : ZMod (4 * n)))
        = (t, (ZMod.castHom hdvd (ZMod (2 * n))) ((n : ℕ) : ZMod (4 * n))) :=
      rfl
    rw [happ, map_natCast]
  · -- kernel = {0, σ̂ + σ̂}
    intro x
    obtain ⟨x₁, x₂⟩ := x
    have happ : (AddMonoidHom.prodMap (AddMonoidHom.id (ZMod m))
        (ZMod.castHom hdvd (ZMod (2 * n))).toAddMonoidHom) (x₁, x₂)
        = (x₁, (ZMod.castHom hdvd (ZMod (2 * n))) x₂) := rfl
    have hσσ : ((t, ((n : ℕ) : ZMod (4 * n))) + (t, ((n : ℕ) : ZMod (4 * n))))
        = ((0 : ZMod m), ((2 * n : ℕ) : ZMod (4 * n))) := by
      rw [Prod.mk_add_mk, ht, ← Nat.cast_add, show n + n = 2 * n by ring]
    rw [happ, hσσ]
    have hval : ((x₂.val : ℕ) : ZMod (4 * n)) = x₂ := by
      rw [ZMod.natCast_val, ZMod.cast_id]
    constructor
    · intro h0
      have h1 : (ZMod.castHom hdvd (ZMod (2 * n))) x₂ = 0 :=
        (Prod.mk_eq_zero.mp h0).2
      have h2 : x₁ = 0 := (Prod.mk_eq_zero.mp h0).1
      have hcast : (ZMod.castHom hdvd (ZMod (2 * n))) x₂
          = ((x₂.val : ℕ) : ZMod (2 * n)) := by
        conv_lhs => rw [← hval]
        rw [map_natCast]
      rw [hcast, ZMod.natCast_eq_zero_iff] at h1
      have hlt : x₂.val < 4 * n := ZMod.val_lt x₂
      obtain ⟨c, hc⟩ := h1
      have hc2 : c < 2 := by
        have h4 : 2 * n * c < 2 * n * 2 := by
          calc 2 * n * c = x₂.val := hc.symm
            _ < 4 * n := hlt
            _ = 2 * n * 2 := by ring
        exact Nat.lt_of_mul_lt_mul_left h4
      interval_cases c
      · left
        have hx2 : x₂ = 0 := by
          rw [← hval, hc, mul_zero, Nat.cast_zero]
        rw [hx2, h2]
        rfl
      · right
        have hx2 : x₂ = ((2 * n : ℕ) : ZMod (4 * n)) := by
          rw [← hval, hc, mul_one]
        rw [hx2, h2]
    · rintro (h0 | h0)
      · have h1 : x₂ = 0 := (Prod.mk_eq_zero.mp h0).2
        have h2 : x₁ = 0 := (Prod.mk_eq_zero.mp h0).1
        rw [h1, h2, map_zero]
        rfl
      · have h1 : x₂ = ((2 * n : ℕ) : ZMod (4 * n)) := (Prod.ext_iff.mp h0).2
        have h2 : x₁ = 0 := (Prod.ext_iff.mp h0).1
        rw [h1, h2, map_natCast, ZMod.natCast_self]
        rfl

/-- **`BocksteinVanishes` for doubled-axis `ZMod` products, second-axis
mirror** — unconditional for y-deck covers (e.g. A19-type). -/
theorem bocksteinVanishes_of_zmod_double_right {n m : ℕ} [NeZero n] [NeZero m]
    (D : XDoubleCoverData (ZMod m × ZMod (2 * n)) H)
    (t : ZMod m) (ht : t + t = 0)
    (hdeck : D.deckS = (t, ((n : ℕ) : ZMod (2 * n)))) :
    D.BocksteinVanishes :=
  D.bocksteinVanishes_of_elementForm
    (D.elementForm_of_zmod_double_right t ht hdeck)

/-- **The Bockstein rank equality for doubled-axis `ZMod` products,
second-axis mirror**: `dim (1+σ)·H₁(cover) = k̃ − k`, unconditionally,
for y-deck covers. -/
theorem finrank_range_epsH1_eq_of_zmod_double_right {n m : ℕ}
    [NeZero n] [NeZero m]
    (D : XDoubleCoverData (ZMod m × ZMod (2 * n)) H)
    (t : ZMod m) (ht : t + t = 0)
    (hdeck : D.deckS = (t, ((n : ℕ) : ZMod (2 * n)))) :
    dim₂ (LinearMap.range D.epsH1)
      = dim₂ D.coverComplex.H1
        - dim₂ D.baseComplex.H1 :=
  D.finrank_range_epsH1_eq
    (D.bocksteinVanishes_of_zmod_double_right t ht hdeck)

end XDoubleCoverData

end BB
end Homological
end Stabilizer
end Quantum
