import Mathlib.Tactic
import QEC.Stabilizer.Framework.Core.Stabilizer.StabilizerGroup
import QEC.Stabilizer.Framework.Core.Stabilizer.SubgroupLemmas
import QEC.Stabilizer.Framework.Core.CSS.CSSNoNegI
import QEC.Stabilizer.Framework.Core.Stabilizer.Centralizer
import QEC.Stabilizer.Framework.Core.CSS.CSSCommutationLemmas
import QEC.Stabilizer.Foundations.PauliGroup.Commutation
import QEC.Stabilizer.Foundations.PauliGroup.CommutationTactics
import QEC.Stabilizer.Foundations.BinarySymplectic.Core
import QEC.Stabilizer.Foundations.BinarySymplectic.CheckMatrix
import QEC.Stabilizer.Foundations.BinarySymplectic.CheckMatrixDecidable
import QEC.Stabilizer.Framework.Symplectic.SymplecticSpan
import QEC.Stabilizer.Framework.Core.Stabilizer.StabilizerCode
import QEC.Stabilizer.Framework.Core.CodeNotation
import QEC.Stabilizer.Framework.Symplectic.IndependentEquiv
import QEC.Stabilizer.Foundations.BinarySymplectic.SymplecticInner
import QEC.Stabilizer.Foundations.PauliGroup.NQubitOperator

namespace Quantum
open scoped BigOperators
open scoped Pauli

namespace StabilizerGroup
namespace Steane7

/-!
# The Steane [[7,1,3]] code (CSS stabilizer generators)

We use the standard CSS presentation coming from the classical [7,4,3] Hamming
code.

Let the parity-check rows (supports) be:
- r₁ = {0,1,2,4}
- r₂ = {0,1,3,5}
- r₃ = {0,2,3,6}

Then the Steane stabilizer is generated by:
- Z-checks: Z on each row support (3 generators)
- X-checks: X on each row support (3 generators)

Cross-commutation holds because every Z-row intersects every X-row in an even
number of qubits. We package the resulting subgroup as a `StabilizerGroup 7`.
-/

open NQubitPauliGroupElement

/-!
## Generators
-/

/-- Z-check on row r₁ = {0,1,2,4}: Z on qubits 0,1,2,4 and I elsewhere. -/
def Z1 : NQubitPauliGroupElement 7 := σ[ZZZIZII]

/-- Z-check on row r₂ = {0,1,3,5}: Z on qubits 0,1,3,5 and I elsewhere. -/
def Z2 : NQubitPauliGroupElement 7 := σ[ZZIZIZI]

/-- Z-check on row r₃ = {0,2,3,6}: Z on qubits 0,2,3,6 and I elsewhere. -/
def Z3 : NQubitPauliGroupElement 7 := σ[ZIZZIIZ]

/-- X-check on row r₁ = {0,1,2,4}: X on qubits 0,1,2,4 and I elsewhere. -/
def X1 : NQubitPauliGroupElement 7 := σ[XXXIXII]

/-- X-check on row r₂ = {0,1,3,5}: X on qubits 0,1,3,5 and I elsewhere. -/
def X2 : NQubitPauliGroupElement 7 := σ[XXIXIXI]

/-- X-check on row r₃ = {0,2,3,6}: X on qubits 0,2,3,6 and I elsewhere. -/
def X3 : NQubitPauliGroupElement 7 := σ[XIXXIIX]

/-- The three Z-check generators (Z on each parity-check row). -/
def ZGenerators : Set (NQubitPauliGroupElement 7) :=
  {Z1, Z2, Z3}

/-- The three X-check generators (X on each parity-check row). -/
def XGenerators : Set (NQubitPauliGroupElement 7) :=
  {X1, X2, X3}

/-- The full generator set: Z-checks and X-checks. -/
def generators : Set (NQubitPauliGroupElement 7) :=
  ZGenerators ∪ XGenerators

/-- The Steane stabilizer subgroup: closure of the six generators. -/
noncomputable def subgroup : Subgroup (NQubitPauliGroupElement 7) :=
  Subgroup.closure generators

/-!
## Typing facts: Z-type / X-type generators

Each generator is a `σ[…]` literal, so once the type predicates are unfolded
to "phase `0`, and `I`-or-`Z` (resp. `I`-or-`X`) at each of the seven
positions" the claim is a closed decidable statement.
-/

/-- Each Z-generator is Z-type (I or Z on each qubit). -/
lemma ZGenerators_are_ZType :
    ∀ g, g ∈ ZGenerators → NQubitPauliGroupElement.IsZTypeElement g := by
  unfold IsZTypeElement NQubitPauliOperator.IsZType PauliOperator.IsZType
  rintro g (rfl | rfl | rfl) <;> decide

/-- Each X-generator is X-type (I or X on each qubit). -/
lemma XGenerators_are_XType :
    ∀ g, g ∈ XGenerators → NQubitPauliGroupElement.IsXTypeElement g := by
  unfold IsXTypeElement NQubitPauliOperator.IsXType PauliOperator.IsXType
  rintro g (rfl | rfl | rfl) <;> decide

/-!
## Cross-commutation: Z generators commute with X generators

Each pair is a closed identity between two literal group elements, so `decide`
settles it: the kernel multiplies out both sides through the global
`DecidableEq (NQubitPauliGroupElement n)` instance. Mathematically, a Z-row and
an X-row meet in an even number of qubits (`r₁ ∩ r₂ = {0, 1}`,
`r₁ ∩ r₃ = {0, 2}`, `r₂ ∩ r₃ = {0, 3}`, and each row with itself in four).
-/

/-- Every Z-generator commutes with every X-generator (even intersection of row
supports). -/
lemma ZGenerators_commute_XGenerators :
    ∀ z ∈ ZGenerators, ∀ x ∈ XGenerators, z * x = x * z := by
  rintro z (rfl | rfl | rfl) x (rfl | rfl | rfl) <;> decide

/-!
## Pairwise commutation of all generators
-/

/-- All six generators pairwise commute: same-type pairs by the CSS typing
lemmas, cross-type pairs by `ZGenerators_commute_XGenerators`. -/
theorem generators_commute :
    ∀ g ∈ generators, ∀ h ∈ generators, g * h = h * g := by
  rintro g (hgZ | hgX) h (hhZ | hhX)
  · exact CSSCommutationLemmas.ZType_commutes (ZGenerators_are_ZType g hgZ)
      (ZGenerators_are_ZType h hhZ)
  · exact ZGenerators_commute_XGenerators g hgZ h hhX
  · exact (ZGenerators_commute_XGenerators h hhZ g hgX).symm
  · exact CSSCommutationLemmas.XType_commutes (XGenerators_are_XType g hgX)
      (XGenerators_are_XType h hhX)

/-!
## No `-I` in the Steane stabilizer subgroup (CSS lemma)
-/

/-- The Steane subgroup does not contain −I (CSS lemma with Z- and
X-generators). -/
theorem negIdentity_not_mem : negIdentity 7 ∉ subgroup :=
  CSS.negIdentity_not_mem_closure_union ZGenerators XGenerators
    ZGenerators_are_ZType XGenerators_are_XType ZGenerators_commute_XGenerators

/-- Generators as a list (for symplectic-span arguments and bundled stabilizer
group). -/
def generatorsList : List (NQubitPauliGroupElement 7) :=
  [Z1, Z2, Z3, X1, X2, X3]

/-- The list of generators has the same elements as the generator set. -/
lemma listToSet_generatorsList :
    NQubitPauliGroupElement.listToSet generatorsList = generators := by
  simp only [generatorsList, generators, ZGenerators, XGenerators, listToSet_cons, listToSet_nil,
    LawfulSingleton.insert_empty_eq, Set.insert_union, Set.singleton_union]

/-!
## Bundled `StabilizerGroup 7`
-/

/-- Steane code as `StabilizerGroup 7` (canonical: from generator list). -/
noncomputable def stabilizerGroup : StabilizerGroup 7 :=
  mkStabilizerFromGenerators 7 generatorsList
    (by rw [listToSet_generatorsList]; exact generators_commute)
    (by rw [listToSet_generatorsList]; exact negIdentity_not_mem)

lemma stabilizerGroup_toSubgroup_eq : stabilizerGroup.toSubgroup = subgroup :=
  congrArg Subgroup.closure listToSet_generatorsList

/-!
## Logical operators

Logical X = X on all 7 qubits, logical Z = Z on all 7 qubits. They commute with
the stabilizer, anticommute with each other, and are not in the subgroup (proved
via symplectic span).
-/

/-- Every element of the generators list has phase power 0. -/
lemma AllPhaseZero_generatorsList : NQubitPauliGroupElement.AllPhaseZero generatorsList := by
  simp only [generatorsList, AllPhaseZero_cons, AllPhaseZero_nil, and_true]
  exact ⟨rfl, rfl, rfl, rfl, rfl, rfl⟩

/-- The check-matrix rows of the Steane generators are linearly independent. -/
theorem rowsLinearIndependent_generatorsList :
    NQubitPauliGroupElement.rowsLinearIndependent generatorsList := by decide

/-- The Steane generator list is an independent generating set. -/
theorem GeneratorsIndependent_7_generatorsList : GeneratorsIndependent 7 generatorsList :=
  GeneratorsIndependent_of_rowsLinearIndependent 7 generatorsList
    rowsLinearIndependent_generatorsList

/-- Logical X: X on all seven qubits. -/
def logicalX : NQubitPauliGroupElement 7 :=
  ⟨0, NQubitPauliOperator.X 7⟩

/-- Logical Z: Z on all seven qubits. -/
def logicalZ : NQubitPauliGroupElement 7 :=
  ⟨0, NQubitPauliOperator.Z 7⟩

/-- Logical Y with the convention `Ȳ = i X̄ Z̄`. -/
noncomputable def logicalY : NQubitPauliGroupElement 7 :=
  NQubitPauliGroupElement.phaseI 7 * (logicalX * logicalZ)

/-- Steane logical `Ȳ` is phase-2 all-`Y`, under the convention `Ȳ = i X̄ Z̄`.
-/
lemma logicalY_eq_phase2_allY :
    logicalY = ({ phasePower := (2 : Fin 4), operators := NQubitPauliOperator.Y 7 } :
      NQubitPauliGroupElement 7) := by
  decide

/-- Logical X and logical Z anticommute (symplectic inner product 1 mod 2). -/
theorem logicalX_anticommutes_logicalZ : NQubitPauliGroupElement.Anticommute logicalX logicalZ :=
  NQubitPauliOperator.allX_allZ_anticommute 7 (by decide)

/-- Logical X commutes with every element of the stabilizer: it suffices to
check the six generators, each a closed identity settled by `decide`. -/
theorem logicalX_mem_centralizer : logicalX ∈ centralizer stabilizerGroup := by
  rw [StabilizerGroup.mem_centralizer_iff, stabilizerGroup_toSubgroup_eq, subgroup,
    Subgroup.forall_comm_closure_iff]
  rintro s ((rfl | rfl | rfl) | (rfl | rfl | rfl)) <;> decide

/-- Logical Z commutes with every element of the stabilizer (same argument as
`logicalX_mem_centralizer`). -/
theorem logicalZ_mem_centralizer : logicalZ ∈ centralizer stabilizerGroup := by
  rw [StabilizerGroup.mem_centralizer_iff, stabilizerGroup_toSubgroup_eq, subgroup,
    Subgroup.forall_comm_closure_iff]
  rintro s ((rfl | rfl | rfl) | (rfl | rfl | rfl)) <;> decide

/-!
## StabilizerCode [[7, 1]]

The bare code is its stabilizer group: six independent, pairwise commuting
generators on seven qubits, hence one logical qubit. The chosen logical pair
`(X̄, Z̄)` is bundled separately, in `stabilizerCodeWithLogicals`.
-/

/-- The Steane code as a stabilizer code [[7, 1]]: one logical qubit. -/
noncomputable def stabilizerCode : Code[[7, 1]] where
  hk := by decide
  generatorsList := generatorsList
  generators_length := rfl
  generators_phaseZero := AllPhaseZero_generatorsList
  generators_independent := GeneratorsIndependent_7_generatorsList
  generators_commute := by rw [listToSet_generatorsList]; exact generators_commute
  closure_no_neg_identity := by rw [listToSet_generatorsList]; exact negIdentity_not_mem

/-- The Steane code with its canonical logical basis `X̄ = X⊗⁷`, `Z̄ = Z⊗⁷`. -/
noncomputable def stabilizerCodeWithLogicals : Code[[7, 1]]ₗ where
  toStabilizerCode := stabilizerCode
  logicalOps := fun _ =>
    ⟨logicalX, logicalZ, logicalX_mem_centralizer, logicalZ_mem_centralizer,
      logicalX_anticommutes_logicalZ⟩
  logical_commute_cross := fun ℓ ℓ' h => (h (Subsingleton.elim ℓ ℓ')).elim

end Steane7
end StabilizerGroup

end Quantum
