import QEC.Stabilizer.Core.StabilizerGroup
import QEC.Stabilizer.Core.Centralizer
import QEC.Stabilizer.Core.LogicalOperators
import QEC.Stabilizer.Core.SubgroupLemmas
import QEC.Stabilizer.PauliGroup.Commutation
import QEC.Stabilizer.BinarySymplectic.CheckMatrix
import QEC.Stabilizer.BinarySymplectic.IndependentEquiv

namespace Quantum
namespace StabilizerGroup

variable {n k : ℕ}

/-!
# Stabilizer codes [[n, k]]

A **stabilizer code** encoding k logical qubits on n physical qubits consists of:

1. A stabilizer group S (abelian, no −I) with **exactly n − k independent generators**, so the
   code space has dimension 2^k.

2. For each logical qubit ℓ : Fin k, a pair of logical operators X̄ℓ and Z̄ℓ that:
   - Lie in the centralizer of S (commute with every stabilizer element).
   - Anticommute with each other (X̄ℓ Z̄ℓ = −Z̄ℓ X̄ℓ).
   - Commute with all logical operators for other logical qubits ℓ′ ≠ ℓ.
   - Are not in S (so they act nontrivially on the code space).

This structure captures the standard [[n, k, d]] notion (without distance d).
-/

/-!
## Independent generators (Prop)

Independence is stated as a Prop so that proofs can be carried out using the check-matrix
representation (e.g. `rowsLinearIndependent`) and then lifted here.
-/

/-- A list of n-qubit Pauli group elements is an independent generating set if no element
    lies in the subgroup generated by the others. Prove this by showing the check-matrix
    rows are linearly independent (over ZMod 2), then use
    `GeneratorsIndependent_of_rowsLinearIndependent`. -/
def GeneratorsIndependent (n : ℕ) (L : List (NQubitPauliGroupElement n)) : Prop :=
  Subgroup.IndependentGenerators (NQubitPauliGroupElement.listToSet L)

/-- If the check-matrix rows of `L` are linearly independent, then `L` is an
    independent generating set. Use this to prove `GeneratorsIndependent n L` by
    proving `NQubitPauliGroupElement.rowsLinearIndependent L`. -/
theorem GeneratorsIndependent_of_rowsLinearIndependent (n : ℕ)
    (L : List (NQubitPauliGroupElement n))
    (h : NQubitPauliGroupElement.rowsLinearIndependent L) :
    GeneratorsIndependent n L :=
  NQubitPauliGroupElement.rowsLinearIndependent_implies_independentGenerators L h

/-- A stabilizer code encoding k logical qubits on n physical qubits.

    Requires k ≤ n. The stabilizer is given by a generating list of length n − k whose
    rows (symplectic vectors) are linearly independent. The logical operators are
    indexed by Fin k and satisfy the usual Pauli algebra per logical qubit, with
    cross-commutation between different logical qubits.
-/
structure StabilizerCode (n k : ℕ) where
  /-- We need k ≤ n so that n - k generator count is meaningful. -/
  hk : k ≤ n
  /-- The underlying stabilizer group. -/
  toStabilizerGroup : StabilizerGroup n
  /-- A list of generators whose closure is the stabilizer subgroup. -/
  generatorsList : List (NQubitPauliGroupElement n)
  /-- The stabilizer subgroup equals the closure of the generator list. -/
  subgroup_eq_closure :
    Subgroup.closure (NQubitPauliGroupElement.listToSet generatorsList) =
      toStabilizerGroup.toSubgroup
  /-- There are exactly n - k generators (so the code space has dimension 2^k). -/
  generators_length : generatorsList.length = n - k
  /-- Every generator has phase power 0 (for symplectic representation). -/
  generators_phaseZero : NQubitPauliGroupElement.AllPhaseZero generatorsList
  /-- The generator list is independent (prove via check-matrix: rowsLinearIndependent). -/
  generators_independent : GeneratorsIndependent n generatorsList
  /-- Logical X for each of the k logical qubits. -/
  logicalX : Fin k → NQubitPauliGroupElement n
  /-- Logical Z for each of the k logical qubits. -/
  logicalZ : Fin k → NQubitPauliGroupElement n
  /-- Each logical X is in the centralizer. -/
  logicalX_mem_centralizer : ∀ ℓ, logicalX ℓ ∈ centralizer toStabilizerGroup
  /-- Each logical Z is in the centralizer. -/
  logicalZ_mem_centralizer : ∀ ℓ, logicalZ ℓ ∈ centralizer toStabilizerGroup
  /-- Within each logical qubit, X̄ and Z̄ anticommute. -/
  logicalX_anticommute_logicalZ : ∀ ℓ, NQubitPauliGroupElement.Anticommute (logicalX ℓ) (logicalZ ℓ)
  /-- Logical operators for different logical qubits commute. -/
  logical_commute_cross :
    ∀ ℓ ℓ', ℓ ≠ ℓ' →
      (logicalX ℓ) * (logicalX ℓ') = (logicalX ℓ') * (logicalX ℓ) ∧
      (logicalX ℓ) * (logicalZ ℓ') = (logicalZ ℓ') * (logicalX ℓ) ∧
      (logicalZ ℓ) * (logicalX ℓ') = (logicalX ℓ') * (logicalZ ℓ) ∧
      (logicalZ ℓ) * (logicalZ ℓ') = (logicalZ ℓ') * (logicalZ ℓ)

namespace StabilizerCode

/-- Logical X for qubit ℓ is not in the stabilizer subgroup. -/
theorem logicalX_not_mem_subgroup (C : StabilizerCode n k) (ℓ : Fin k) :
    C.logicalX ℓ ∉ C.toStabilizerGroup.toSubgroup :=
  not_mem_stabilizer_of_anticommutes_centralizer C.toStabilizerGroup (C.logicalX ℓ) (C.logicalZ ℓ)
    (C.logicalZ_mem_centralizer ℓ) (C.logicalX_anticommute_logicalZ ℓ)

/-- Logical Z for qubit ℓ is not in the stabilizer subgroup. -/
theorem logicalZ_not_mem_subgroup (C : StabilizerCode n k) (ℓ : Fin k) :
    C.logicalZ ℓ ∉ C.toStabilizerGroup.toSubgroup :=
  not_mem_stabilizer_of_anticommutes_centralizer C.toStabilizerGroup (C.logicalZ ℓ) (C.logicalX ℓ)
    (C.logicalX_mem_centralizer ℓ)
    (NQubitPauliGroupElement.anticommute_symm (C.logicalX ℓ) (C.logicalZ ℓ)
      (C.logicalX_anticommute_logicalZ ℓ))

/-- Each logical X is a nontrivial logical operator. -/
theorem logicalX_nontrivial (C : StabilizerCode n k) (ℓ : Fin k) :
    IsNontrivialLogicalOperator (C.logicalX ℓ) C.toStabilizerGroup :=
  ⟨C.logicalX_mem_centralizer ℓ, C.logicalX_not_mem_subgroup ℓ⟩

/-- Each logical Z is a nontrivial logical operator. -/
theorem logicalZ_nontrivial (C : StabilizerCode n k) (ℓ : Fin k) :
    IsNontrivialLogicalOperator (C.logicalZ ℓ) C.toStabilizerGroup :=
  ⟨C.logicalZ_mem_centralizer ℓ, C.logicalZ_not_mem_subgroup ℓ⟩

/-- The generator set is an independent generating set for the stabilizer. -/
theorem generators_independentGenerators (C : StabilizerCode n k) :
    Subgroup.IndependentGenerators (NQubitPauliGroupElement.listToSet C.generatorsList) :=
  C.generators_independent

end StabilizerCode

end StabilizerGroup
end Quantum
