import QEC.Stabilizer.Framework.Core.Stabilizer.StabilizerGroup
import QEC.Stabilizer.Framework.Core.Stabilizer.Centralizer
import QEC.Stabilizer.Framework.Core.Logical.LogicalOperators
import QEC.Stabilizer.Framework.Core.Stabilizer.SubgroupLemmas
import QEC.Stabilizer.Foundations.PauliGroup.Commutation
import QEC.Stabilizer.Foundations.BinarySymplectic.CheckMatrix
import QEC.Stabilizer.Framework.Symplectic.IndependentEquiv

namespace Quantum
namespace StabilizerGroup

variable {n k : ℕ}

/-!
# Stabilizer codes [[n, k]]

A **stabilizer code** encoding k logical qubits on n physical qubits *is* its
stabilizer group S (abelian, no −I), presented by **exactly n − k independent
generators**, so the code space has dimension 2^k. That is the whole
definition: `StabilizerCode n k` bundles the generator list with the proofs
that it is independent, pairwise commuting, phase-zero, and does not generate
−I. Code distance (`HasCodeDistance`, in `Logical/CodeDistance.lean`) is a
property of this bare code, since it only quantifies over the nontrivial
logical operators of S.

A **logical basis** is derived data rather than part of the definition: for
each logical qubit ℓ : Fin k, a pair of logical operators X̄ℓ and Z̄ℓ that

- lie in the centralizer of S (commute with every stabilizer element),
- anticommute with each other (X̄ℓ Z̄ℓ = −Z̄ℓ X̄ℓ),
- commute with all logical operators for other logical qubits ℓ′ ≠ ℓ, and
- are not in S (so they act nontrivially on the code space).

`StabilizerCodeWithLogicals n k` extends `StabilizerCode n k` with such a
basis, for the constructions that genuinely consume one (logical Clifford
actions, the encoding step of code concatenation, the `k = 1` centralizer
classification).
-/

/-!
## Independent generators (Prop)

Independence is stated as a Prop so that proofs can be carried out using the
check-matrix representation (e.g. `rowsLinearIndependent`) and then lifted here.
-/

/-- A list of n-qubit Pauli group elements is an independent generating set if
no element
    lies in the subgroup generated by the others. Prove this by showing the check-matrix
    rows are linearly independent (over ZMod 2), then use
    `GeneratorsIndependent_of_rowsLinearIndependent`. -/
def GeneratorsIndependent (n : ℕ) (L : List (NQubitPauliGroupElement n)) : Prop :=
  Subgroup.IndependentGenerators (NQubitPauliGroupElement.listToSet L)

/-- If the check-matrix rows of `L` are linearly independent, then `L` is an
    independent generating set. Use this to prove `GeneratorsIndependent n L` by
    proving `NQubitPauliGroupElement.rowsLinearIndependent L`. -/
theorem GeneratorsIndependent_of_rowsLinearIndependent (n : ℕ)
    (L : List (NQubitPauliGroupElement n))
    (h : NQubitPauliGroupElement.rowsLinearIndependent L) :
    GeneratorsIndependent n L :=
  NQubitPauliGroupElement.rowsLinearIndependent_implies_independentGenerators L h

/-!
## Stabilizer group from generators

The stabilizer is defined as the closure of the generator list (single source of
truth).
-/

/-- Build a stabilizer group from a list of generators that pairwise commute and
whose
    closure does not contain -I. -/
noncomputable def mkStabilizerFromGenerators (n : ℕ) (L : List (NQubitPauliGroupElement n))
    (h_comm : ∀ g ∈ NQubitPauliGroupElement.listToSet L,
      ∀ h ∈ NQubitPauliGroupElement.listToSet L, g * h = h * g)
    (h_no_neg : negIdentity n ∉ Subgroup.closure (NQubitPauliGroupElement.listToSet L)) :
    StabilizerGroup n where
  toSubgroup := Subgroup.closure (NQubitPauliGroupElement.listToSet L)
  is_abelian := fun g h hg hh =>
    Subgroup.abelian_closure_of_pairwise_commute
      (NQubitPauliGroupElement.listToSet L) h_comm g hg h hh
  no_neg_identity := h_no_neg

/-!
## The bare code: `StabilizerCode n k`
-/

/-- A stabilizer code encoding k logical qubits on n physical qubits: n − k
independent, pairwise commuting, phase-zero generators whose closure does not
contain −I. The generator list is the single source of truth; the stabilizer
group itself is `StabilizerCode.toStabilizerGroup`.

No logical operators are bundled here — a choice of logical basis is derived
data, carried by `StabilizerCodeWithLogicals`. -/
structure StabilizerCode (n k : ℕ) where
  /-- We need k ≤ n so that n - k generator count is meaningful. -/
  hk : k ≤ n
  /-- A list of generators whose closure is the stabilizer subgroup. -/
  generatorsList : List (NQubitPauliGroupElement n)
  /-- There are exactly n - k generators (so the code space has dimension 2^k).
  -/
  generators_length : generatorsList.length = n - k
  /-- Every generator has phase power 0 (for symplectic/check-matrix
representation). -/
  generators_phaseZero : NQubitPauliGroupElement.AllPhaseZero generatorsList
  /-- The generator list is independent (prove via check-matrix:
rowsLinearIndependent). -/
  generators_independent : GeneratorsIndependent n generatorsList
  /-- Generators pairwise commute. -/
  generators_commute : ∀ g ∈ NQubitPauliGroupElement.listToSet generatorsList,
    ∀ h ∈ NQubitPauliGroupElement.listToSet generatorsList, g * h = h * g
  /-- The closure of the generators does not contain -I. -/
  closure_no_neg_identity : negIdentity n ∉ Subgroup.closure
    (NQubitPauliGroupElement.listToSet generatorsList)

namespace StabilizerCode

/-- The stabilizer group of the code (derived from the generator list). -/
noncomputable def toStabilizerGroup (C : StabilizerCode n k) : StabilizerGroup n :=
  mkStabilizerFromGenerators n C.generatorsList C.generators_commute C.closure_no_neg_identity

/-- The generator set is an independent generating set for the stabilizer. -/
theorem generators_independentGenerators (C : StabilizerCode n k) :
    Subgroup.IndependentGenerators (NQubitPauliGroupElement.listToSet C.generatorsList) :=
  C.generators_independent

end StabilizerCode

/-!
## A code with a chosen logical basis: `StabilizerCodeWithLogicals n k`
-/

/-- A stabilizer code together with a chosen logical basis: for each logical
qubit, a `LogicalQubitOps` pair (X̄ℓ, Z̄ℓ) in the centralizer of the stabilizer
and anticommuting with each other, with the pairs of distinct logical qubits
commuting. `extends StabilizerCode n k`, so every field and lemma of the bare
code is available through dot notation, and `toStabilizerCode` forgets the
basis. -/
structure StabilizerCodeWithLogicals (n k : ℕ) extends StabilizerCode n k where
  /-- For each logical qubit, logical X and Z in the centralizer, anticommuting.
  -/
  logicalOps : Fin k → LogicalQubitOps n (mkStabilizerFromGenerators n generatorsList
    generators_commute closure_no_neg_identity)
  /-- Logical operators for different logical qubits commute. -/
  logical_commute_cross : ∀ ℓ ℓ', ℓ ≠ ℓ' →
    ((logicalOps ℓ).xOp * (logicalOps ℓ').xOp = (logicalOps ℓ').xOp * (logicalOps ℓ).xOp ∧
      (logicalOps ℓ).xOp * (logicalOps ℓ').zOp = (logicalOps ℓ').zOp * (logicalOps ℓ).xOp ∧
      (logicalOps ℓ).zOp * (logicalOps ℓ').xOp = (logicalOps ℓ').xOp * (logicalOps ℓ).zOp ∧
      (logicalOps ℓ).zOp * (logicalOps ℓ').zOp = (logicalOps ℓ').zOp * (logicalOps ℓ).zOp)

namespace StabilizerCodeWithLogicals

/-- Logical X for logical qubit ℓ, i.e. `(C.logicalOps ℓ).xOp`. A reducible
abbreviation, so `simp` sees through it and lemmas may be stated in either
spelling; there is deliberately no display rewriting between the two — a goal
prints whichever spelling its term carries. -/
abbrev logicalX (C : StabilizerCodeWithLogicals n k) (ℓ : Fin k) : NQubitPauliGroupElement n :=
  (C.logicalOps ℓ).xOp

/-- Logical Z for logical qubit ℓ, i.e. `(C.logicalOps ℓ).zOp` (see `logicalX`).
-/
abbrev logicalZ (C : StabilizerCodeWithLogicals n k) (ℓ : Fin k) : NQubitPauliGroupElement n :=
  (C.logicalOps ℓ).zOp

/-- Logical X for qubit ℓ is not in the stabilizer subgroup. -/
theorem logicalX_not_mem_subgroup (C : StabilizerCodeWithLogicals n k) (ℓ : Fin k) :
    C.logicalX ℓ ∉ C.toStabilizerGroup.toSubgroup :=
  (C.logicalOps ℓ).xOp_not_mem

/-- Logical Z for qubit ℓ is not in the stabilizer subgroup. -/
theorem logicalZ_not_mem_subgroup (C : StabilizerCodeWithLogicals n k) (ℓ : Fin k) :
    C.logicalZ ℓ ∉ C.toStabilizerGroup.toSubgroup :=
  (C.logicalOps ℓ).zOp_not_mem

/-- Each logical X is a nontrivial logical operator. -/
theorem logicalX_nontrivial (C : StabilizerCodeWithLogicals n k) (ℓ : Fin k) :
    IsNontrivialLogicalOperator (C.logicalX ℓ) C.toStabilizerGroup :=
  (C.logicalOps ℓ).xOp_nontrivial

/-- Each logical Z is a nontrivial logical operator. -/
theorem logicalZ_nontrivial (C : StabilizerCodeWithLogicals n k) (ℓ : Fin k) :
    IsNontrivialLogicalOperator (C.logicalZ ℓ) C.toStabilizerGroup :=
  (C.logicalOps ℓ).zOp_nontrivial

end StabilizerCodeWithLogicals

end StabilizerGroup
end Quantum
