import QEC.Stabilizer.Framework.Core.Stabilizer.StabilizerGroup
import QEC.Stabilizer.Framework.Core.Stabilizer.Centralizer
import QEC.Stabilizer.Framework.Core.Logical.CodeDistance
import QEC.Stabilizer.Foundations.PauliGroup.NQubitOperator
import QEC.Stabilizer.Foundations.PauliGroup.NQubitElement
import QEC.Stabilizer.Foundations.PauliGroup.Commutation
import QEC.Stabilizer.Foundations.PauliGroupSingle
import QEC.Stabilizer.Foundations.BinarySymplectic.SymplecticInner

namespace Quantum
namespace StabilizerGroup

variable {n : ℕ}

open NQubitPauliGroupElement
open PauliOperator

/-!
# CSS code distance helpers

If for every qubit and every non-identity single-qubit Pauli at that qubit there is a
generator that anticommutes with the corresponding weight-1 element, then no weight-1
Pauli lies in the centralizer. This is used to prove no weight-1 logicals for CSS codes.
-/

/-- The weight-1 group element at qubit `i` with single-qubit Pauli `P` (phase 0). -/
def weightOneAt (i : Fin n) (P : PauliOperator) : NQubitPauliGroupElement n :=
  ofOperator (fun k => if k = i then P else .I)

/-- If for every qubit `i` and every single-qubit Pauli `P ≠ I` there exists a generator
    in `genSet` that anticommutes with the weight-1 element at `i` with Pauli `P`, then
    no weight-1 Pauli is in the centralizer of the stabilizer group generated by `genSet`. -/
theorem no_weight_one_mem_centralizer_of_anticommute_witness (S : StabilizerGroup n)
    (genSet : Set (NQubitPauliGroupElement n))
    (h_closure : S.toSubgroup = Subgroup.closure genSet)
    (h_anticomm : ∀ i : Fin n, ∀ P : PauliOperator, P ≠ .I →
      ∃ g ∈ genSet, Anticommute (weightOneAt i P) g)
    (g : NQubitPauliGroupElement n) (hg : weight g = 1)
    (h_cent : g ∈ centralizer S) : False := by
  rw [mem_centralizer_iff_closure g S genSet h_closure] at h_cent
  have h_supp_card : (support g).card = 1 := by
    rw [support, ← NQubitPauliOperator.weight, ← weight]; exact hg
  obtain ⟨i, hi⟩ := Finset.card_eq_one.mp h_supp_card
  have hi_supp : support g = {i} := hi
  have hi_ne_I : g.operators i ≠ .I := by
    have : i ∈ support g := by rw [hi_supp]; exact Finset.mem_singleton_self i
    exact (mem_support g i).mp this
  have hop : g.operators = fun k => if k = i then g.operators i else .I := by
    ext k
    by_cases hk : k = i
    · simp [hk]
    · have hk' : k ∉ support g := by rw [hi_supp, Finset.mem_singleton]; exact hk
      have h_op_k : g.operators k = .I := by by_contra h; exact hk' ((mem_support g k).mpr h)
      simp only [hk, if_false, h_op_k]
  obtain ⟨s, hs_mem, h_anti⟩ := h_anticomm i (g.operators i) hi_ne_I
  have heq : g.operators = (weightOneAt i (g.operators i)).operators := by
    simp only [weightOneAt, ofOperator_operators]; exact hop
  have h_anti_g : Anticommute g s := by
    rw [anticommutes_iff_mulOp_phasePower] at h_anti
    rw [anticommutes_iff_mulOp_phasePower]; rw [heq]; exact h_anti
  have h_comm : s * g = g * s := h_cent s hs_mem
  unfold Anticommute at h_anti_g
  rw [← h_comm, ← negIdentity_eq_minusOne n] at h_anti_g
  have h_neg : negIdentity n = 1 := by
    have H : (s * g) = negIdentity n * (s * g) := h_anti_g
    calc negIdentity n = negIdentity n * 1 := (NQubitPauliGroupElement.mul_one _).symm
      _ = negIdentity n * ((s * g) * (s * g)⁻¹) := by rw [mul_inv_cancel]
      _ = (negIdentity n * (s * g)) * (s * g)⁻¹ := by
          rw [NQubitPauliGroupElement.mul_assoc (negIdentity n) (s * g) (s * g)⁻¹]
      _ = (s * g) * (s * g)⁻¹ := by rw [← H]
      _ = 1 := by rw [mul_inv_cancel]
  exact negIdentity_ne_one n h_neg

/-! ## Weight-2 anticommute witness

Mirror of the weight-1 helper above for distance-3 codes (where ruling out
weight-1 *and* weight-2 logicals is required). The shape is the same: given
a witness function from qubit-pairs and Pauli-pairs to generators that
anticommute with the corresponding weight-2 element, conclude no weight-2
Pauli lies in the centralizer.

First exerciser: the [[5,1,3]] five-qubit perfect code in
`Codes/FiveQubit_5_1_3.lean`. -/

/-- The weight-2 group element at qubits `i ≠ j` with single-qubit Paulis
`P` at qubit `i` and `Q` at qubit `j` (phase 0). -/
def weightTwoAt (i j : Fin n) (P Q : PauliOperator) : NQubitPauliGroupElement n :=
  ofOperator (fun k => if k = i then P else if k = j then Q else .I)

/-- If for every pair of distinct qubits `i ≠ j` and every pair of
non-identity single-qubit Paulis `P, Q` there exists a generator in
`genSet` that anticommutes with the corresponding weight-2 element, then
no weight-2 Pauli is in the centralizer of the stabilizer group generated
by `genSet`. -/
theorem no_weight_two_mem_centralizer_of_anticommute_witness (S : StabilizerGroup n)
    (genSet : Set (NQubitPauliGroupElement n))
    (h_closure : S.toSubgroup = Subgroup.closure genSet)
    (h_anticomm : ∀ i j : Fin n, i ≠ j → ∀ P Q : PauliOperator, P ≠ .I → Q ≠ .I →
      ∃ g ∈ genSet, Anticommute (weightTwoAt i j P Q) g)
    (g : NQubitPauliGroupElement n) (hg : weight g = 2)
    (h_cent : g ∈ centralizer S) : False := by
  rw [mem_centralizer_iff_closure g S genSet h_closure] at h_cent
  have h_supp_card : (support g).card = 2 := by
    rw [support, ← NQubitPauliOperator.weight, ← weight]; exact hg
  obtain ⟨i, j, hij, hsupp⟩ := Finset.card_eq_two.mp h_supp_card
  -- g.operators are non-identity at i and j, identity elsewhere
  have hi_ne_I : g.operators i ≠ .I := by
    have : i ∈ support g := by rw [hsupp]; exact Finset.mem_insert_self i {j}
    exact (mem_support g i).mp this
  have hj_ne_I : g.operators j ≠ .I := by
    have : j ∈ support g := by rw [hsupp]; simp
    exact (mem_support g j).mp this
  have hop : g.operators =
      fun k => if k = i then g.operators i else if k = j then g.operators j else .I := by
    ext k
    by_cases hki : k = i
    · subst hki; simp
    · by_cases hkj : k = j
      · subst hkj; simp [hki]
      · have hk' : k ∉ support g := by
          rw [hsupp]; simp [hki, hkj]
        have h_op_k : g.operators k = .I := by
          by_contra h; exact hk' ((mem_support g k).mpr h)
        simp [hki, hkj, h_op_k]
  obtain ⟨s, hs_mem, h_anti⟩ := h_anticomm i j hij (g.operators i) (g.operators j) hi_ne_I hj_ne_I
  have heq : g.operators = (weightTwoAt i j (g.operators i) (g.operators j)).operators := by
    simp only [weightTwoAt, ofOperator_operators]; exact hop
  have h_anti_g : Anticommute g s := by
    rw [anticommutes_iff_mulOp_phasePower] at h_anti
    rw [anticommutes_iff_mulOp_phasePower]; rw [heq]; exact h_anti
  have h_comm : s * g = g * s := h_cent s hs_mem
  unfold Anticommute at h_anti_g
  rw [← h_comm, ← negIdentity_eq_minusOne n] at h_anti_g
  have h_neg : negIdentity n = 1 := by
    have H : (s * g) = negIdentity n * (s * g) := h_anti_g
    calc negIdentity n = negIdentity n * 1 := (NQubitPauliGroupElement.mul_one _).symm
      _ = negIdentity n * ((s * g) * (s * g)⁻¹) := by rw [mul_inv_cancel]
      _ = (negIdentity n * (s * g)) * (s * g)⁻¹ := by
          rw [NQubitPauliGroupElement.mul_assoc (negIdentity n) (s * g) (s * g)⁻¹]
      _ = (s * g) * (s * g)⁻¹ := by rw [← H]
      _ = 1 := by rw [mul_inv_cancel]
  exact negIdentity_ne_one n h_neg

/-! ## Distance-2 packaging

Combines `hasCodeDistance_of` (the general "prove distance by witness + min-weight"
schema in `Framework/Core/Logical/CodeDistance.lean`) with the weight-1 anticommute
helper above, specialized to `d = 2`. The only positive weight strictly less than 2
is `w = 1`, so a single anticommute-witness function suffices to rule out the
nontrivial-low-weight side, and a single explicit weight-2 logical handles the
realizer side.

Saves the `interval_cases w; rcases (IsNontrivialLogicalOperator_iff …).mp …; exact`
boilerplate that every distance-2 CSS code instantiates verbatim.

Use sites: `Codes/Small/FourQubit_4_2_2.lean` ([[4,2,2]]),
`Codes/Small/CSS_4_1_2.lean` ([[4,1,2]] LNCY), and any future small CSS
detection code (the iceberg family `[[2m, 2m-2, 2]]` is next in the engineering
queue). -/

/-- Distance-2 from an anticommute witness. Given a CSS-style stabilizer code
`C`, a generating set `genSet` whose closure is `C.toStabilizerGroup`, a witness
function ruling out weight-1 elements in the centralizer (the `h_anticomm`
predicate, same as for `no_weight_one_mem_centralizer_of_anticommute_witness`),
and an explicit weight-2 nontrivial logical, conclude `HasCodeDistance C 2`. -/
theorem hasCodeDistance_two_of_anticommute_witness {k : ℕ} (C : StabilizerCode n k)
    (genSet : Set (NQubitPauliGroupElement n))
    (h_closure : C.toStabilizerGroup.toSubgroup = Subgroup.closure genSet)
    (h_anticomm : ∀ i : Fin n, ∀ P : PauliOperator, P ≠ .I →
      ∃ g ∈ genSet, Anticommute (weightOneAt i P) g)
    (h_witness : ∃ g, IsNontrivialLogicalOperator g C.toStabilizerGroup ∧ weight g = 2) :
    HasCodeDistance C 2 := by
  refine hasCodeDistance_of C 2 (by decide) h_witness ?_
  intro w hw_pos hw_lt g hg_weight h_nontrivial
  interval_cases w
  -- w = 1: g has weight 1; show g cannot lie in the centralizer.
  rcases (IsNontrivialLogicalOperator_iff g C.toStabilizerGroup).mp h_nontrivial
    with ⟨h_cent, _, _⟩
  exact no_weight_one_mem_centralizer_of_anticommute_witness C.toStabilizerGroup
    genSet h_closure h_anticomm g hg_weight h_cent

/-! ## Anticommutation of weight-1 and weight-2 elements, qubit by qubit

`weightOneAt i P` and `weightTwoAt i j P Q` are the identity away from the named qubits, so the
symplectic inner product with any `g` — which decides anticommutation, by
`anticommutes_iff_symplectic_inner_one` — collapses to one or two single-qubit terms. -/

/-- A weight-one Pauli anticommutes with `g` iff its single qubit does. -/
theorem anticommute_weightOneAt_iff (i : Fin n) (P : PauliOperator)
    (g : NQubitPauliGroupElement n) :
    Anticommute (weightOneAt i P) g ↔ symplecticProductSingle P (g.operators i) = 1 := by
  rw [NQubitPauliOperator.anticommutes_iff_symplectic_inner_one,
    NQubitPauliOperator.symplecticInner,
    Finset.sum_eq_single i (fun k _ hk => by simp [weightOneAt, hk]) (by simp)]
  simp [weightOneAt]

/-- A weight-two Pauli anticommutes with `g` iff exactly one of its two qubits does. -/
theorem anticommute_weightTwoAt_iff {i j : Fin n} (hij : i ≠ j) (P Q : PauliOperator)
    (g : NQubitPauliGroupElement n) :
    Anticommute (weightTwoAt i j P Q) g ↔
      symplecticProductSingle P (g.operators i) +
        symplecticProductSingle Q (g.operators j) = 1 := by
  rw [NQubitPauliOperator.anticommutes_iff_symplectic_inner_one,
    NQubitPauliOperator.symplecticInner,
    Finset.sum_eq_add i j hij (fun k _ hk => by simp [weightTwoAt, hk.1, hk.2]) (by simp) (by simp)]
  simp [weightTwoAt, hij.symm]

/-! ## CSS checks as supports

A CSS generator is `Z` (or `X`) along a row of the classical parity-check matrix and the
identity elsewhere. `zOn S` / `xOn S` name that element by its support `S`, so that a CSS code's
generators can be handed to the distance closers below as a family of `Finset`s. -/

/-- The phase-0 element acting as `Z` on every qubit of `S` and trivially elsewhere. -/
def zOn (S : Finset (Fin n)) : NQubitPauliGroupElement n :=
  ofOperator fun k => if k ∈ S then .Z else .I

/-- The phase-0 element acting as `X` on every qubit of `S` and trivially elsewhere. -/
def xOn (S : Finset (Fin n)) : NQubitPauliGroupElement n :=
  ofOperator fun k => if k ∈ S then .X else .I

@[simp] lemma zOn_operators (S : Finset (Fin n)) (k : Fin n) :
    (zOn S).operators k = if k ∈ S then .Z else .I := rfl

@[simp] lemma xOn_operators (S : Finset (Fin n)) (k : Fin n) :
    (xOn S).operators k = if k ∈ S then .X else .I := rfl

/-- A `Z`-check on `S` detects the weight-one Pauli `P` at `i` iff `i ∈ S` and `P` has an
`X`-component (`P = X` or `P = Y`, i.e. `X`-bit `1`). -/
lemma anticommute_weightOneAt_zOn_iff (i : Fin n) (P : PauliOperator) (S : Finset (Fin n)) :
    Anticommute (weightOneAt i P) (zOn S) ↔ i ∈ S ∧ P.toSymplecticSingle.1 = 1 := by
  rw [anticommute_weightOneAt_iff]
  by_cases hi : i ∈ S <;> simp [hi]

/-- An `X`-check on `S` detects the weight-one Pauli `P` at `i` iff `i ∈ S` and `P` has a
`Z`-component (`P = Z` or `P = Y`, i.e. `Z`-bit `1`). -/
lemma anticommute_weightOneAt_xOn_iff (i : Fin n) (P : PauliOperator) (S : Finset (Fin n)) :
    Anticommute (weightOneAt i P) (xOn S) ↔ i ∈ S ∧ P.toSymplecticSingle.2 = 1 := by
  rw [anticommute_weightOneAt_iff]
  by_cases hi : i ∈ S <;> simp [hi]

/-- A `Z`-check on `S` detects a weight-two Pauli iff the `X`-bits it sees (at `i` if `i ∈ S`,
at `j` if `j ∈ S`) sum to `1`. -/
lemma anticommute_weightTwoAt_zOn_iff {i j : Fin n} (hij : i ≠ j) (P Q : PauliOperator)
    (S : Finset (Fin n)) :
    Anticommute (weightTwoAt i j P Q) (zOn S) ↔
      (if i ∈ S then P.toSymplecticSingle.1 else 0) +
        (if j ∈ S then Q.toSymplecticSingle.1 else 0) = 1 := by
  rw [anticommute_weightTwoAt_iff hij]
  by_cases hi : i ∈ S <;> by_cases hj : j ∈ S <;> simp [hi, hj]

/-- An `X`-check on `S` detects a weight-two Pauli iff the `Z`-bits it sees sum to `1`. -/
lemma anticommute_weightTwoAt_xOn_iff {i j : Fin n} (hij : i ≠ j) (P Q : PauliOperator)
    (S : Finset (Fin n)) :
    Anticommute (weightTwoAt i j P Q) (xOn S) ↔
      (if i ∈ S then P.toSymplecticSingle.2 else 0) +
        (if j ∈ S then Q.toSymplecticSingle.2 else 0) = 1 := by
  rw [anticommute_weightTwoAt_iff hij]
  by_cases hi : i ∈ S <;> by_cases hj : j ∈ S <;> simp [hi, hj]

/-! ## Distance-3 packaging for CSS codes: the column condition

The classical picture. Write a Pauli `E` as an `X`-support `A` (the qubits carrying `X` or `Y`)
and a `Z`-support `B` (those carrying `Z` or `Y`). `E` commutes with the `Z`-check on row `S`
iff `|A ∩ S|` is even, and with the `X`-check on `S` iff `|B ∩ S|` is even. So `E` goes
undetected iff `A` is a codeword of the classical code with check rows `zRow` and `B` one of the
code with check rows `xRow`. If both classical codes have distance `≥ 3` — every column of the
check matrix is nonzero (`_cover`: each qubit lies on some row) and any two columns are distinct
(`_sep`: any two qubits are separated by some row) — then a codeword of weight `≤ 2` is zero, so
`|A|, |B| ≤ 2` forces `A = B = ∅`: no Pauli of weight `1` or `2` is undetected.

The two theorems below are that argument at weights one and two, phrased as the anticommute
witness functions consumed by `no_weight_one_mem_centralizer_of_anticommute_witness` and
`no_weight_two_mem_centralizer_of_anticommute_witness`; `hasCodeDistance_three_of_columns`
packages them with a weight-3 witness. First exerciser: the Steane `[[7,1,3]]` code
(`Codes/Small/Steane7Distance.lean`), whose Hamming check matrix has exactly the seven nonzero
columns of length three. -/

section Columns

variable {ι κ : Type*} (zRow : ι → Finset (Fin n)) (xRow : κ → Finset (Fin n))
  (genSet : Set (NQubitPauliGroupElement n))

/-- No weight-one Pauli goes undetected when every qubit lies on a `Z`-row and on an `X`-row. -/
theorem weight_one_anticomm_witness_of_columns
    (hz : ∀ r, zOn (zRow r) ∈ genSet) (hx : ∀ c, xOn (xRow c) ∈ genSet)
    (hz_cover : ∀ i, ∃ r, i ∈ zRow r) (hx_cover : ∀ i, ∃ c, i ∈ xRow c) :
    ∀ i : Fin n, ∀ P : PauliOperator, P ≠ .I →
      ∃ g ∈ genSet, Anticommute (weightOneAt i P) g := by
  intro i P hP
  rcases toSymplecticSingle_fst_eq_zero_or_one P with hPx | hPx
  · -- `P = Z`: any `X`-row through `i` detects it.
    obtain ⟨c, hc⟩ := hx_cover i
    exact ⟨xOn (xRow c), hx c, (anticommute_weightOneAt_xOn_iff i P _).mpr
      ⟨hc, toSymplecticSingle_snd_eq_one_of_fst_eq_zero hP hPx⟩⟩
  · -- `P ∈ {X, Y}`: any `Z`-row through `i` detects it.
    obtain ⟨r, hr⟩ := hz_cover i
    exact ⟨zOn (zRow r), hz r, (anticommute_weightOneAt_zOn_iff i P _).mpr ⟨hr, hPx⟩⟩

/-- No weight-two Pauli goes undetected when, in addition, any two qubits are separated by a
`Z`-row and by an `X`-row. -/
theorem weight_two_anticomm_witness_of_columns
    (hz : ∀ r, zOn (zRow r) ∈ genSet) (hx : ∀ c, xOn (xRow c) ∈ genSet)
    (hz_cover : ∀ i, ∃ r, i ∈ zRow r)
    (hz_sep : ∀ i j, i ≠ j → ∃ r, (i ∈ zRow r ↔ j ∉ zRow r))
    (hx_sep : ∀ i j, i ≠ j → ∃ c, (i ∈ xRow c ↔ j ∉ xRow c)) :
    ∀ i j : Fin n, i ≠ j → ∀ P Q : PauliOperator, P ≠ .I → Q ≠ .I →
      ∃ g ∈ genSet, Anticommute (weightTwoAt i j P Q) g := by
  intro i j hij P Q hP hQ
  rcases toSymplecticSingle_fst_eq_zero_or_one P with hPx | hPx <;>
    rcases toSymplecticSingle_fst_eq_zero_or_one Q with hQx | hQx
  · -- `P = Q = Z`: an `X`-row separating `i` from `j` sees exactly one of them.
    obtain ⟨c, hc⟩ := hx_sep i j hij
    refine ⟨xOn (xRow c), hx c, (anticommute_weightTwoAt_xOn_iff hij P Q _).mpr ?_⟩
    rw [toSymplecticSingle_snd_eq_one_of_fst_eq_zero hP hPx,
      toSymplecticSingle_snd_eq_one_of_fst_eq_zero hQ hQx]
    by_cases hi : i ∈ xRow c <;> simp_all
  · -- Only `Q` has an `X`-component: a `Z`-row through `j` sees it alone.
    obtain ⟨r, hr⟩ := hz_cover j
    refine ⟨zOn (zRow r), hz r, (anticommute_weightTwoAt_zOn_iff hij P Q _).mpr ?_⟩
    simp [hr, hPx, hQx]
  · -- Only `P` has an `X`-component: a `Z`-row through `i` sees it alone.
    obtain ⟨r, hr⟩ := hz_cover i
    refine ⟨zOn (zRow r), hz r, (anticommute_weightTwoAt_zOn_iff hij P Q _).mpr ?_⟩
    simp [hr, hPx, hQx]
  · -- Both have an `X`-component: a `Z`-row separating `i` from `j` sees exactly one.
    obtain ⟨r, hr⟩ := hz_sep i j hij
    refine ⟨zOn (zRow r), hz r, (anticommute_weightTwoAt_zOn_iff hij P Q _).mpr ?_⟩
    rw [hPx, hQx]
    by_cases hi : i ∈ zRow r <;> simp_all

/-- **Distance 3 from the column condition.** A CSS stabilizer code `C`, generated by `genSet`,
whose `Z`-checks `zOn (zRow r)` and `X`-checks `xOn (xRow c)` lie in `genSet`, has distance
exactly `3` as soon as both check matrices have nonzero, pairwise distinct columns (classical
distance `≥ 3` on each side) and some nontrivial logical of weight `3` is exhibited. -/
theorem hasCodeDistance_three_of_columns {k : ℕ} (C : StabilizerCode n k)
    (h_closure : C.toStabilizerGroup.toSubgroup = Subgroup.closure genSet)
    (hz : ∀ r, zOn (zRow r) ∈ genSet) (hx : ∀ c, xOn (xRow c) ∈ genSet)
    (hz_cover : ∀ i, ∃ r, i ∈ zRow r) (hx_cover : ∀ i, ∃ c, i ∈ xRow c)
    (hz_sep : ∀ i j, i ≠ j → ∃ r, (i ∈ zRow r ↔ j ∉ zRow r))
    (hx_sep : ∀ i j, i ≠ j → ∃ c, (i ∈ xRow c ↔ j ∉ xRow c))
    (h_witness : ∃ g, IsNontrivialLogicalOperator g C.toStabilizerGroup ∧ weight g = 3) :
    HasCodeDistance C 3 := by
  refine hasCodeDistance_of C 3 (by decide) h_witness ?_
  intro w hw_pos hw_lt g hg_weight h_nontrivial
  rcases (IsNontrivialLogicalOperator_iff g C.toStabilizerGroup).mp h_nontrivial
    with ⟨h_cent, _, _⟩
  interval_cases w
  · exact no_weight_one_mem_centralizer_of_anticommute_witness C.toStabilizerGroup genSet
      h_closure (weight_one_anticomm_witness_of_columns zRow xRow genSet hz hx hz_cover hx_cover)
      g hg_weight h_cent
  · exact no_weight_two_mem_centralizer_of_anticommute_witness C.toStabilizerGroup genSet
      h_closure (weight_two_anticomm_witness_of_columns zRow xRow genSet hz hx hz_cover hz_sep
        hx_sep) g hg_weight h_cent

end Columns

end StabilizerGroup
end Quantum
