/-
CLASS-F FILE — the `floor_kcombo` dispatch body is machine-emitted by
qec-lab:experiments/bb_lab/scripts/gen_assembly_2d.py (fragments pasted in by hand);
the surrounding shell and the capstone theorems are hand-maintained.
Regenerate fragments rather than hand-editing dispatch rows.
-/
/-
# Phase 6: assembling `MImBound` — the 2-D-orbit dispatch

(The human-facing capstones live in `Gross/Distance.lean`.)
`floor_kcombo` dispatches an arbitrary `ker ∂₂` class `kcombo c` over its 64 free-cell values:
the zero class is vacuous (`seamC 0 = 0`, so the coset is a boundary, contradicting the
hypothesis), and each of the 63 nonzero classes is a `(j,k)`-translate of one of the **5**
full-translation-orbit representatives (`MImFloorY0, Y1, Y4, Y11, Y12`), whose floor transports
via `floor_transfer` (`MImTransport §17`).  Pure `y`-shifts use a zero defect; the general
`x`-shift carries an explicit boundary defect `mkZeta …` (the §9.3 cut-shift, absorbed into the
re-indexed free chain).  `mimBound_holds` then reduces any `ζ ∈ ker ∂₂` to `kcombo` form
(`kerBasis_spans`) and applies the dispatch — discharging the last assumed `Prop` of the Gross
`[[144,12,12]]` distance proof.  The per-class shifts + boundary defects are generated by
`qec-lab:experiments/bb_lab/scripts/gen_assembly_2d.py` (the 2-D variant of `gen_assembly.py`).
-/
import QEC.Stabilizer.Codes.BivariateBicycle.Gross.SafeFloor.MImTransport
import QEC.Stabilizer.Codes.BivariateBicycle.Gross.StabilizerCode
import QEC.Stabilizer.Codes.BivariateBicycle.Gross.SafeFloor.MImFloorY0
import QEC.Stabilizer.Codes.BivariateBicycle.Gross.SafeFloor.MImFloorY1
import QEC.Stabilizer.Codes.BivariateBicycle.Gross.SafeFloor.MImFloorY4
import QEC.Stabilizer.Codes.BivariateBicycle.Gross.SafeFloor.MImFloorY11
import QEC.Stabilizer.Codes.BivariateBicycle.Gross.SafeFloor.MImFloorY12

open Quantum.Stabilizer.Homological.BB
open Quantum.Stabilizer.Homological.BB.LightStab

namespace Quantum.Stabilizer.Homological.BB.LightStab

set_option maxRecDepth 4096

/-- `seamC` is additive, so it kills `0`. -/
theorem seamC_zero : seamC 0 = 0 := by
  have h : seamC 0 + seamC 0 = seamC 0 + 0 := by rw [← seamC_add, add_zero, add_zero]
  exact add_left_cancel h

/-- The all-zero `kcombo` is the zero class. -/
theorem kcombo_zero : kcombo 0 0 0 0 0 0 = 0 := by funext h; simp [kcombo]

/-- The two values of `ZMod 2` (case-split with literal substitution). -/
theorem zmod2_cases (c : ZMod 2) : c = 0 ∨ c = 1 := by revert c; decide

set_option synthInstance.maxSize 4000 in
-- The `Decidable` instance for the 63-way `∧` (63 function-equality leaves) is a
-- term far larger than the default `synthInstance.maxSize` of 128; the search
-- itself is cheap.
/-- The 63 class-level covariance certificates
`seamC z' = T_c (seamC zrep) + ∂₂ δ` consumed by `floor_kcombo`, bundled into a
single kernel `decide`: every `seamC` is read through its packed mask
(`seamC_kcombo_mask`) and every `∂₂` through its sparse form, so the 63 function
equalities are 63 cheap `Nat` walks. -/
private theorem transfer_covs :
    (seamC (kcombo 0 0 0 0 0 1)
          = translate1 ((1, 5) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,1),(5,5)])) ∧
    (seamC (kcombo 0 0 0 0 1 0)
          = translate1 ((1, 0) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,0),(5,4)])) ∧
    (seamC (kcombo 0 0 0 0 1 1)
          = translate1 ((4, 1) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(0,0),(0,1),(0,2),(0,5),(1,1),(1,5)])) ∧
    (seamC (kcombo 0 0 0 1 0 0)
          = translate1 ((2, 4) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(4,0),(4,2),(5,1),(5,3)])) ∧
    (seamC (kcombo 0 0 0 1 0 1)
          = translate1 ((0, 3) : BaseGroup) (seamC Y4.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 0 0 0 1 1 0)
          = translate1 ((1, 0) : BaseGroup) (seamC Y0.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,0),(5,1),(5,3),(5,4)])) ∧
    (seamC (kcombo 0 0 0 1 1 1)
          = translate1 ((3, 4) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB
                (mkZeta [(3,0),(3,2),(4,1),(4,3),(5,0),(5,3),(5,4),(5,5)])) ∧
    (seamC (kcombo 0 0 1 0 0 0)
          = translate1 ((0, 0) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 0 0 1 0 0 1)
          = translate1 ((1, 0) : BaseGroup) (seamC Y4.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,0),(5,1),(5,2),(5,5)])) ∧
    (seamC (kcombo 0 0 1 0 1 0)
          = translate1 ((2, 3) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(4,1),(4,3),(5,2),(5,4)])) ∧
    (seamC (kcombo 0 0 1 0 1 1)
          = translate1 ((1, 2) : BaseGroup) (seamC Y0.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,1),(5,2),(5,4),(5,5)])) ∧
    (seamC (kcombo 0 0 1 1 0 0)
          = translate1 ((1, 5) : BaseGroup) (seamC Y4.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,0),(5,1),(5,2),(5,3)])) ∧
    (seamC (kcombo 0 0 1 1 0 1)
          = translate1 ((1, 1) : BaseGroup) (seamC Y0.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,0),(5,2),(5,3),(5,5)])) ∧
    (seamC (kcombo 0 0 1 1 1 0)
          = translate1 ((5, 5) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(0,1),(0,3)])) ∧
    (seamC (kcombo 0 0 1 1 1 1)
          = translate1 ((3, 5) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB
                (mkZeta [(3,1),(3,5),(4,0),(4,2),(5,2),(5,3),(5,4),(5,5)])) ∧
    (seamC (kcombo 0 1 0 0 0 0)
          = translate1 ((0, 1) : BaseGroup) (seamC Y0.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 0 1 0 0 0 1)
          = translate1 ((0, 1) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 0 1 0 0 1 0)
          = translate1 ((2, 1) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(4,3),(4,5),(5,0),(5,4)])) ∧
    (seamC (kcombo 0 1 0 0 1 1)
          = translate1 ((1, 1) : BaseGroup) (seamC Y4.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,0),(5,1),(5,4),(5,5)])) ∧
    (seamC (kcombo 0 1 0 1 0 0)
          = translate1 ((1, 3) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,1),(5,3)])) ∧
    (seamC (kcombo 0 1 0 1 0 1)
          = translate1 ((1, 1) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,3),(5,5)])) ∧
    (seamC (kcombo 0 1 0 1 1 0)
          = translate1 ((0, 0) : BaseGroup) (seamC Y11.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 0 1 0 1 1 1)
          = translate1 ((4, 2) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(0,0),(0,1),(0,4),(0,5),(1,0),(1,4)])) ∧
    (seamC (kcombo 0 1 1 0 0 0)
          = translate1 ((2, 5) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(4,1),(4,5),(5,0),(5,2)])) ∧
    (seamC (kcombo 0 1 1 0 0 1)
          = translate1 ((3, 2) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB
                (mkZeta [(3,2),(3,4),(4,3),(4,5),(5,0),(5,1),(5,2),(5,5)])) ∧
    (seamC (kcombo 0 1 1 0 1 0)
          = translate1 ((0, 4) : BaseGroup) (seamC Y4.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 0 1 1 0 1 1)
          = translate1 ((0, 2) : BaseGroup) (seamC Y12.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 0 1 1 1 0 0)
          = translate1 ((5, 0) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(0,0),(0,2)])) ∧
    (seamC (kcombo 0 1 1 1 0 1)
          = translate1 ((2, 1) : BaseGroup) (seamC Y0.zrep)
            + bbBoundary2Fn baseA baseB
                (mkZeta [(1,0),(1,2),(1,3),(1,5),(2,0),(2,2),(2,3),(2,5)])) ∧
    (seamC (kcombo 0 1 1 1 1 0)
          = translate1 ((3, 0) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB
                (mkZeta [(3,0),(3,4),(4,1),(4,5),(5,1),(5,2),(5,3),(5,4)])) ∧
    (seamC (kcombo 0 1 1 1 1 1)
          = translate1 ((1, 3) : BaseGroup) (seamC Y4.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,2),(5,3),(5,4),(5,5)])) ∧
    (seamC (kcombo 1 0 0 0 0 0)
          = translate1 ((0, 0) : BaseGroup) (seamC Y0.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 0 0 0 0 1)
          = translate1 ((2, 0) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(4,0),(4,4),(5,1),(5,5)])) ∧
    (seamC (kcombo 1 0 0 0 1 0)
          = translate1 ((0, 2) : BaseGroup) (seamC Y4.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 0 0 0 1 1)
          = translate1 ((3, 3) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB
                (mkZeta [(3,1),(3,3),(4,2),(4,4),(5,0),(5,1),(5,4),(5,5)])) ∧
    (seamC (kcombo 1 0 0 1 0 0)
          = translate1 ((0, 5) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 0 0 1 0 1)
          = translate1 ((2, 2) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(4,2),(4,4),(5,3),(5,5)])) ∧
    (seamC (kcombo 1 0 0 1 1 0)
          = translate1 ((2, 0) : BaseGroup) (seamC Y0.zrep)
            + bbBoundary2Fn baseA baseB
                (mkZeta [(1,0),(1,1),(1,3),(1,4),(2,0),(2,1),(2,3),(2,4)])) ∧
    (seamC (kcombo 1 0 0 1 1 1)
          = translate1 ((1, 2) : BaseGroup) (seamC Y4.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,0),(5,3),(5,4),(5,5)])) ∧
    (seamC (kcombo 1 0 1 0 0 0)
          = translate1 ((1, 4) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,0),(5,2)])) ∧
    (seamC (kcombo 1 0 1 0 0 1)
          = translate1 ((4, 0) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(0,0),(0,1),(0,2),(0,3),(1,0),(1,2)])) ∧
    (seamC (kcombo 1 0 1 0 1 0)
          = translate1 ((1, 2) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,2),(5,4)])) ∧
    (seamC (kcombo 1 0 1 0 1 1)
          = translate1 ((0, 2) : BaseGroup) (seamC Y11.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 0 1 1 0 0)
          = translate1 ((3, 1) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB
                (mkZeta [(3,3),(3,5),(4,0),(4,4),(5,0),(5,1),(5,2),(5,3)])) ∧
    (seamC (kcombo 1 0 1 1 0 1)
          = translate1 ((0, 1) : BaseGroup) (seamC Y12.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 0 1 1 1 0)
          = translate1 ((1, 4) : BaseGroup) (seamC Y4.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(5,1),(5,2),(5,3),(5,4)])) ∧
    (seamC (kcombo 1 0 1 1 1 1)
          = translate1 ((5, 4) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(0,2),(0,4)])) ∧
    (seamC (kcombo 1 1 0 0 0 0)
          = translate1 ((0, 2) : BaseGroup) (seamC Y0.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 1 0 0 0 1)
          = translate1 ((0, 1) : BaseGroup) (seamC Y4.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 1 0 0 1 0)
          = translate1 ((0, 2) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 1 0 0 1 1)
          = translate1 ((5, 2) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(0,0),(0,4)])) ∧
    (seamC (kcombo 1 1 0 1 0 0)
          = translate1 ((0, 5) : BaseGroup) (seamC Y4.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 1 0 1 0 1)
          = translate1 ((0, 3) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 1 0 1 1 0)
          = translate1 ((0, 0) : BaseGroup) (seamC Y12.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 1 0 1 1 1)
          = translate1 ((5, 3) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(0,3),(0,5)])) ∧
    (seamC (kcombo 1 1 1 0 0 0)
          = translate1 ((0, 0) : BaseGroup) (seamC Y4.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 1 1 0 0 1)
          = translate1 ((5, 1) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(0,1),(0,5)])) ∧
    (seamC (kcombo 1 1 1 0 1 0)
          = translate1 ((0, 4) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 1 1 0 1 1)
          = translate1 ((2, 2) : BaseGroup) (seamC Y0.zrep)
            + bbBoundary2Fn baseA baseB
                (mkZeta [(1,1),(1,2),(1,4),(1,5),(2,1),(2,2),(2,4),(2,5)])) ∧
    (seamC (kcombo 1 1 1 1 0 0)
          = translate1 ((4, 5) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(0,1),(0,2),(0,3),(0,4),(1,1),(1,3)])) ∧
    (seamC (kcombo 1 1 1 1 0 1)
          = translate1 ((0, 1) : BaseGroup) (seamC Y11.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [])) ∧
    (seamC (kcombo 1 1 1 1 1 0)
          = translate1 ((4, 4) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(0,2),(0,3),(0,4),(0,5),(1,2),(1,4)])) ∧
    (seamC (kcombo 1 1 1 1 1 1)
          = translate1 ((4, 3) : BaseGroup) (seamC Y1.zrep)
            + bbBoundary2Fn baseA baseB (mkZeta [(0,0),(0,3),(0,4),(0,5),(1,3),(1,5)])) := by
  simp only [Y0.zrep, Y1.zrep, Y4.zrep, Y11.zrep, Y12.zrep, seamC_kcombo_mask, bb2_fun_sparse]
  decide +kernel

/-- **The 2-D-orbit dispatch**: every `ker ∂₂` class, addressed by its six
free-cell values, has safe-sector floor `≥ 12` (the zero class is vacuous; the
rest transport to one of the 5 full-orbit reps via `floor_transfer`). -/
theorem floor_kcombo (c0 c1 c2 c3 c4 c5 : ZMod 2) (f : BaseGroup → ZMod 2)
    (hb : seamC (kcombo c0 c1 c2 c3 c4 c5) + bbBoundary2Fn baseA baseB f
      ∉ bb72Complex.boundaries) :
    12 ≤ bb72Complex.chainWeight (seamC (kcombo c0 c1 c2 c3 c4 c5)
      + bbBoundary2Fn baseA baseB f) := by
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12, h13,
    h14, h15, h16, h17, h18, h19, h20, h21, h22, h23, h24, h25, h26,
    h27, h28, h29, h30, h31, h32, h33, h34, h35, h36, h37, h38, h39,
    h40, h41, h42, h43, h44, h45, h46, h47, h48, h49, h50, h51, h52,
    h53, h54, h55, h56, h57, h58, h59, h60, h61, h62, h63⟩ := transfer_covs
  rcases zmod2_cases c0 with rfl | rfl <;> rcases zmod2_cases c1 with rfl | rfl <;>
    rcases zmod2_cases c2 with rfl | rfl <;> rcases zmod2_cases c3 with rfl | rfl <;>
    rcases zmod2_cases c4 with rfl | rfl <;> rcases zmod2_cases c5 with rfl | rfl
  · rw [kcombo_zero, seamC_zero, zero_add] at hb; exact absurd ⟨f, rfl⟩ hb
  · exact floor_transfer Y1.zrep (kcombo 0 0 0 0 0 1) ((1, 5) : BaseGroup)
      (mkZeta [(5,1),(5,5)])
      h1 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 0 0 1 0) ((1, 0) : BaseGroup)
      (mkZeta [(5,0),(5,4)])
      h2 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 0 0 1 1) ((4, 1) : BaseGroup)
      (mkZeta [(0,0),(0,1),(0,2),(0,5),(1,1),(1,5)])
      h3 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 0 1 0 0) ((2, 4) : BaseGroup)
      (mkZeta [(4,0),(4,2),(5,1),(5,3)])
      h4 Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 0 0 0 1 0 1) ((0, 3) : BaseGroup)
      (mkZeta [])
      h5 Y4.floor f
  · exact floor_transfer Y0.zrep (kcombo 0 0 0 1 1 0) ((1, 0) : BaseGroup)
      (mkZeta [(5,0),(5,1),(5,3),(5,4)])
      h6 Y0.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 0 1 1 1) ((3, 4) : BaseGroup)
      (mkZeta [(3,0),(3,2),(4,1),(4,3),(5,0),(5,3),(5,4),(5,5)])
      h7 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 1 0 0 0) ((0, 0) : BaseGroup)
      (mkZeta [])
      h8 Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 0 0 1 0 0 1) ((1, 0) : BaseGroup)
      (mkZeta [(5,0),(5,1),(5,2),(5,5)])
      h9 Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 1 0 1 0) ((2, 3) : BaseGroup)
      (mkZeta [(4,1),(4,3),(5,2),(5,4)])
      h10 Y1.floor f
  · exact floor_transfer Y0.zrep (kcombo 0 0 1 0 1 1) ((1, 2) : BaseGroup)
      (mkZeta [(5,1),(5,2),(5,4),(5,5)])
      h11 Y0.floor f
  · exact floor_transfer Y4.zrep (kcombo 0 0 1 1 0 0) ((1, 5) : BaseGroup)
      (mkZeta [(5,0),(5,1),(5,2),(5,3)])
      h12 Y4.floor f
  · exact floor_transfer Y0.zrep (kcombo 0 0 1 1 0 1) ((1, 1) : BaseGroup)
      (mkZeta [(5,0),(5,2),(5,3),(5,5)])
      h13 Y0.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 1 1 1 0) ((5, 5) : BaseGroup)
      (mkZeta [(0,1),(0,3)])
      h14 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 0 1 1 1 1) ((3, 5) : BaseGroup)
      (mkZeta [(3,1),(3,5),(4,0),(4,2),(5,2),(5,3),(5,4),(5,5)])
      h15 Y1.floor f
  · exact floor_transfer Y0.zrep (kcombo 0 1 0 0 0 0) ((0, 1) : BaseGroup)
      (mkZeta [])
      h16 Y0.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 0 0 0 1) ((0, 1) : BaseGroup)
      (mkZeta [])
      h17 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 0 0 1 0) ((2, 1) : BaseGroup)
      (mkZeta [(4,3),(4,5),(5,0),(5,4)])
      h18 Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 0 1 0 0 1 1) ((1, 1) : BaseGroup)
      (mkZeta [(5,0),(5,1),(5,4),(5,5)])
      h19 Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 0 1 0 0) ((1, 3) : BaseGroup)
      (mkZeta [(5,1),(5,3)])
      h20 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 0 1 0 1) ((1, 1) : BaseGroup)
      (mkZeta [(5,3),(5,5)])
      h21 Y1.floor f
  · exact floor_transfer Y11.zrep (kcombo 0 1 0 1 1 0) ((0, 0) : BaseGroup)
      (mkZeta [])
      h22 Y11.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 0 1 1 1) ((4, 2) : BaseGroup)
      (mkZeta [(0,0),(0,1),(0,4),(0,5),(1,0),(1,4)])
      h23 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 1 0 0 0) ((2, 5) : BaseGroup)
      (mkZeta [(4,1),(4,5),(5,0),(5,2)])
      h24 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 1 0 0 1) ((3, 2) : BaseGroup)
      (mkZeta [(3,2),(3,4),(4,3),(4,5),(5,0),(5,1),(5,2),(5,5)])
      h25 Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 0 1 1 0 1 0) ((0, 4) : BaseGroup)
      (mkZeta [])
      h26 Y4.floor f
  · exact floor_transfer Y12.zrep (kcombo 0 1 1 0 1 1) ((0, 2) : BaseGroup)
      (mkZeta [])
      h27 Y12.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 1 1 0 0) ((5, 0) : BaseGroup)
      (mkZeta [(0,0),(0,2)])
      h28 Y1.floor f
  · exact floor_transfer Y0.zrep (kcombo 0 1 1 1 0 1) ((2, 1) : BaseGroup)
      (mkZeta [(1,0),(1,2),(1,3),(1,5),(2,0),(2,2),(2,3),(2,5)])
      h29 Y0.floor f
  · exact floor_transfer Y1.zrep (kcombo 0 1 1 1 1 0) ((3, 0) : BaseGroup)
      (mkZeta [(3,0),(3,4),(4,1),(4,5),(5,1),(5,2),(5,3),(5,4)])
      h30 Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 0 1 1 1 1 1) ((1, 3) : BaseGroup)
      (mkZeta [(5,2),(5,3),(5,4),(5,5)])
      h31 Y4.floor f
  · exact floor_transfer Y0.zrep (kcombo 1 0 0 0 0 0) ((0, 0) : BaseGroup)
      (mkZeta [])
      h32 Y0.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 0 0 0 1) ((2, 0) : BaseGroup)
      (mkZeta [(4,0),(4,4),(5,1),(5,5)])
      h33 Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 1 0 0 0 1 0) ((0, 2) : BaseGroup)
      (mkZeta [])
      h34 Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 0 0 1 1) ((3, 3) : BaseGroup)
      (mkZeta [(3,1),(3,3),(4,2),(4,4),(5,0),(5,1),(5,4),(5,5)])
      h35 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 0 1 0 0) ((0, 5) : BaseGroup)
      (mkZeta [])
      h36 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 0 1 0 1) ((2, 2) : BaseGroup)
      (mkZeta [(4,2),(4,4),(5,3),(5,5)])
      h37 Y1.floor f
  · exact floor_transfer Y0.zrep (kcombo 1 0 0 1 1 0) ((2, 0) : BaseGroup)
      (mkZeta [(1,0),(1,1),(1,3),(1,4),(2,0),(2,1),(2,3),(2,4)])
      h38 Y0.floor f
  · exact floor_transfer Y4.zrep (kcombo 1 0 0 1 1 1) ((1, 2) : BaseGroup)
      (mkZeta [(5,0),(5,3),(5,4),(5,5)])
      h39 Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 1 0 0 0) ((1, 4) : BaseGroup)
      (mkZeta [(5,0),(5,2)])
      h40 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 1 0 0 1) ((4, 0) : BaseGroup)
      (mkZeta [(0,0),(0,1),(0,2),(0,3),(1,0),(1,2)])
      h41 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 1 0 1 0) ((1, 2) : BaseGroup)
      (mkZeta [(5,2),(5,4)])
      h42 Y1.floor f
  · exact floor_transfer Y11.zrep (kcombo 1 0 1 0 1 1) ((0, 2) : BaseGroup)
      (mkZeta [])
      h43 Y11.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 1 1 0 0) ((3, 1) : BaseGroup)
      (mkZeta [(3,3),(3,5),(4,0),(4,4),(5,0),(5,1),(5,2),(5,3)])
      h44 Y1.floor f
  · exact floor_transfer Y12.zrep (kcombo 1 0 1 1 0 1) ((0, 1) : BaseGroup)
      (mkZeta [])
      h45 Y12.floor f
  · exact floor_transfer Y4.zrep (kcombo 1 0 1 1 1 0) ((1, 4) : BaseGroup)
      (mkZeta [(5,1),(5,2),(5,3),(5,4)])
      h46 Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 0 1 1 1 1) ((5, 4) : BaseGroup)
      (mkZeta [(0,2),(0,4)])
      h47 Y1.floor f
  · exact floor_transfer Y0.zrep (kcombo 1 1 0 0 0 0) ((0, 2) : BaseGroup)
      (mkZeta [])
      h48 Y0.floor f
  · exact floor_transfer Y4.zrep (kcombo 1 1 0 0 0 1) ((0, 1) : BaseGroup)
      (mkZeta [])
      h49 Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 0 0 1 0) ((0, 2) : BaseGroup)
      (mkZeta [])
      h50 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 0 0 1 1) ((5, 2) : BaseGroup)
      (mkZeta [(0,0),(0,4)])
      h51 Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 1 1 0 1 0 0) ((0, 5) : BaseGroup)
      (mkZeta [])
      h52 Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 0 1 0 1) ((0, 3) : BaseGroup)
      (mkZeta [])
      h53 Y1.floor f
  · exact floor_transfer Y12.zrep (kcombo 1 1 0 1 1 0) ((0, 0) : BaseGroup)
      (mkZeta [])
      h54 Y12.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 0 1 1 1) ((5, 3) : BaseGroup)
      (mkZeta [(0,3),(0,5)])
      h55 Y1.floor f
  · exact floor_transfer Y4.zrep (kcombo 1 1 1 0 0 0) ((0, 0) : BaseGroup)
      (mkZeta [])
      h56 Y4.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 1 0 0 1) ((5, 1) : BaseGroup)
      (mkZeta [(0,1),(0,5)])
      h57 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 1 0 1 0) ((0, 4) : BaseGroup)
      (mkZeta [])
      h58 Y1.floor f
  · exact floor_transfer Y0.zrep (kcombo 1 1 1 0 1 1) ((2, 2) : BaseGroup)
      (mkZeta [(1,1),(1,2),(1,4),(1,5),(2,1),(2,2),(2,4),(2,5)])
      h59 Y0.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 1 1 0 0) ((4, 5) : BaseGroup)
      (mkZeta [(0,1),(0,2),(0,3),(0,4),(1,1),(1,3)])
      h60 Y1.floor f
  · exact floor_transfer Y11.zrep (kcombo 1 1 1 1 0 1) ((0, 1) : BaseGroup)
      (mkZeta [])
      h61 Y11.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 1 1 1 0) ((4, 4) : BaseGroup)
      (mkZeta [(0,2),(0,3),(0,4),(0,5),(1,2),(1,4)])
      h62 Y1.floor f
  · exact floor_transfer Y1.zrep (kcombo 1 1 1 1 1 1) ((4, 3) : BaseGroup)
      (mkZeta [(0,0),(0,3),(0,4),(0,5),(1,3),(1,5)])
      h63 Y1.floor f

/-- **`MImBound` holds** — the last assumed `Prop` for unconditional
`d(gross) = 12`. -/
theorem mimBound_holds : MImBound := by
  intro ζ hζ f hb
  have h : ζ = kcombo (ζ (4,4)) (ζ (4,5)) (ζ (5,2)) (ζ (5,3)) (ζ (5,4)) (ζ (5,5)) :=
    (kerBasis_spans ζ hζ).symm.trans (recon_eq_kcombo ζ)
  rw [h] at hb ⊢
  exact floor_kcombo (ζ (4,4)) (ζ (4,5)) (ζ (5,2)) (ζ (5,3)) (ζ (5,4)) (ζ (5,5)) f hb

end Quantum.Stabilizer.Homological.BB.LightStab
