/-
# Phase 6: the weight-24 standard-form walk (A4 §11) — M1a

The slot-frame substrate (`SlotFrame.lean`, §10) is here specialized to the
**standard form** `S(a,b)` (Def 26) and the **standard-form walk** (Prop 29):
`S(a,b) ≥ 6` for all `(a,b) ∈ F₄²`, hence every weight-24 spine cell has linked
block cost `≥ 6 + 6 = 12`.  This is the §11 combinatorial core of the wt-24 floor.

Everything here is **axiom-clean** (kernel `decide`, standard three axioms only —
no `native_decide`/`ofReduceBool`):

* `slotCost v2 v3 v4` — the per-slot cost (Lemma 20), as the exact minimum over
  the free `v₀` (trivial-character, `F₂`) and `v₁` (free unit-side) of the layer
  weight `wt5OfComps`.  Tabled (`SLOTCOST`, 64 entries) for kernel-`decide` speed.
* `slotCost_le` — soundness: `slotCost` lower-bounds the exact per-slot weight
  `wt5OfComps` for every `v₀ ∈ F₂`, `v₁ ∈ F₄` (kernel `decide`, 512 tuples).
* `Sab a b` — the standard form (Def 26): the `v₀`-free block cost with confined
  line `⟨ℓ⟩`, component-3 direction `a·ℓ + c₃`, component-4 direction
  `b·ℓ + ωθ + c₄`, minimized over the free constants `p, c₂, c₃, c₄ ∈ F₄`.
* `Sab_ge_6` — **Proposition 29**: `S(a,b) ≥ 6` for all 16 pairs (kernel `decide`,
  the 256-knob × 4-slot × 16-pair walk; cheap because the tables are packed `Nat`
  literals with kernel-accelerated lookups).

The slot order is `allS = (e,x,y,xy) = (0,0),(1,0),(0,1),(1,1)`; over it the
labeling `ℓ = ellL = Bhat2 = (ω²,ω,1,0) = (3,2,1,0)` (a bijection, `ellL_inj`) and
`ωθ = ω·theta = (2,0,2,0)`; F₄ is `Fin 4` with `(0,1,ω,ω²)=(0,1,2,3)`.

The block-cost reduction (Lemma 27: `L(24a)=S(a₃,a₄)`, `R(24a)≅S(a₃,a₄²)`, …)
and the bridge to the actual coset weight `chainWeight (seamC zrep + ∂₂ f)`
(via `costFromComps`/`exCost`) are M1b, downstream of this file.
-/

import QEC.Stabilizer.Codes.BivariateBicycle.Gross.SafeFloor.SlotFrame

open Quantum.Stabilizer.Homological.BB
open Quantum.Stabilizer.Homological.BB.CRTFrame
open Quantum.Stabilizer.Homological.BB.LightStab

namespace Quantum.Stabilizer.Homological.BB.LightStab

set_option maxRecDepth 8192

/-! ## §11.1 The per-slot cost `slotCost` (Lemma 20) and its soundness

`slotCost v2 v3 v4` is the exact minimum layer weight realizing the constrained
slot datum `(v2, v3, v4)` (the confined `v₂` and the spine `v₃, v₄`), minimized
over the free `v₀ ∈ {0,1}` (`F₂`-valued trivial character) and the free
unit-side `v₁ ∈ F₄`. We pin it as a 64-entry table for kernel-`decide` speed;
`slotCost_le` certifies it is a genuine lower bound on `wt5OfComps`. -/

/-- The per-slot cost table (`v₂*16 + v₃*4 + v₄`),
`= min_{v₀∈F₂, v₁∈F₄} wt5OfComps`. Generated by `#eval` of that minimum over
`SlotFrame`/`MImClassify.wt5OfComps`. -/
def SLOTCOST : Array Nat :=
  #[0,3,3,3,3,2,2,2,3,2,2,2,3,2,2,2,3,2,2,2,2,1,3,3,2,3,3,1,2,3,1,3,
    3,2,2,2,2,3,3,1,2,3,1,3,2,1,3,3,3,2,2,2,2,3,1,3,2,1,3,3,2,3,3,1]

/-- `SLOTCOST` packed into one `Nat` literal at 2 bits per entry (all values are
`≤ 3`), so lookups are kernel-accelerated `Nat` ops; `slotCost_eq_table`
certifies agreement with the array. -/
def SLOTCOST_N : Nat := 0x7ef6deabf6de7eabde7ef6ababababfc

/-- The per-slot cost (Lemma 20): the minimum layer weight for a slot datum
`(v₂, v₃, v₄)`, with the free `v₀`/`v₁` minimized out. -/
def slotCost (v2 v3 v4 : Fin 4) : Nat :=
  (SLOTCOST_N >>> (2 * (v2.val * 16 + v3.val * 4 + v4.val))) &&& 3

/-- The packed table agrees with the readable `SLOTCOST` array (kernel `decide`,
64 entries). -/
theorem slotCost_eq_table : ∀ v2 v3 v4 : Fin 4,
    slotCost v2 v3 v4 = SLOTCOST.getD (v2.val * 16 + v3.val * 4 + v4.val) 99 := by decide

/-- **Slot-cost soundness (Lemma 20).** `slotCost` lower-bounds the exact
per-slot layer weight `wt5OfComps` for every free `v₀ ∈ F₂` and `v₁ ∈ F₄`.
Kernel `decide` over the 512 value-tuples — **axiom-clean** (no
`native_decide`). -/
theorem slotCost_le : ∀ (v0 : Fin 2) (v1 v2 v3 v4 : Fin 4),
    slotCost v2 v3 v4 ≤ wt5OfComps (v0.castLE (by norm_num)) v1 v2 v3 v4 := by decide

/-! ### The L-block per-slot cost `slotCostL` (the bridge counterpart)

The A/left block (repo `leftHalf`) has unit multipliers at components `0` and
`2` (`chainWeight_coset_eq`: `(unitHat, Ahat1, unitHat, Ahat1, Ahat4)`), so its
free components are `0, 2` and its constrained slot datum is `(v₁, v₃, v₄)`. Its
per-slot cost is therefore the minimum over `v₀ ∈ F₂`, `v₂ ∈ F₄` (the dual of
`slotCost`, which frees `v₀, v₁` for the B/right block).

The M1b bridge sums these per-slot bounds:
`exCost ≥ ∑ₛ slotCostL(L₁,L₃,L₄) + ∑ₛ slotCost(R₂,R₃,R₄)`. **This per-slot sum
alone is NOT enough** — minimized over the spine it reaches only `9` for the
(non-standard-offset) `Y4` rep, because (a) the block costs are not yet `S(a,b)`
(the offsets need the Lemma-27 reduction to standard form) and (b) it frees the
*shared* `V₀` independently per block, discarding the parity coupling (Remark 3:
both blocks `≡ |V₀| mod 2`). Closing to `12` therefore needs the standard-form
reduction + the shared-`V₀` assembly, exactly the §11 structure — the remaining
M1b work. -/

/-- The L-block per-slot cost table (`v₁*16 + v₃*4 + v₄`),
`= min_{v₀∈F₂, v₂∈F₄} wt5OfComps`. -/
def SLOTCOSTL : Array Nat :=
  #[0,3,3,3,3,2,2,2,3,2,2,2,3,2,2,2,3,2,2,2,2,1,3,3,2,3,1,3,2,3,3,1,
    3,2,2,2,2,3,1,3,2,3,3,1,2,1,3,3,3,2,2,2,2,3,3,1,2,1,3,3,2,3,1,3]

/-- `SLOTCOSTL` packed into one `Nat` literal at 2 bits per entry (cf.
`SLOTCOST_N`); `slotCostL_eq_table` certifies agreement with the array. -/
def SLOTCOSTL_N : Nat := 0xdef67eabf67edeab7edef6ababababfc

/-- The A/left-block per-slot cost: the minimum layer weight for the constrained
slot datum `(v₁, v₃, v₄)`, with the free `v₀ ∈ F₂` and `v₂ ∈ F₄` minimized out.
-/
def slotCostL (v1 v3 v4 : Fin 4) : Nat :=
  (SLOTCOSTL_N >>> (2 * (v1.val * 16 + v3.val * 4 + v4.val))) &&& 3

/-- The packed table agrees with the readable `SLOTCOSTL` array (kernel
`decide`, 64 entries). -/
theorem slotCostL_eq_table : ∀ v1 v3 v4 : Fin 4,
    slotCostL v1 v3 v4 = SLOTCOSTL.getD (v1.val * 16 + v3.val * 4 + v4.val) 99 := by decide

/-- **L-block slot-cost soundness.** `slotCostL` lower-bounds the exact per-slot
layer weight for every free `v₀ ∈ F₂`, `v₂ ∈ F₄` (kernel `decide`, axiom-clean).
-/
theorem slotCostL_le : ∀ (v0 : Fin 2) (v1 v2 v3 v4 : Fin 4),
    slotCostL v1 v3 v4 ≤ wt5OfComps (v0.castLE (by norm_num)) v1 v2 v3 v4 := by decide

/-! ## §11.2 The standard form `S(a,b)` (Def 26) and the walk (Prop 29)

`S(a,b)` is the `v₀`-free block cost in standard form: over the four slots `s`
(where `ℓ(s)` ranges over all of `F₄`, as `ℓ` is a bijection), the confined
`v₂ = p·ℓ + c₂`, the spine `v₃ = a·ℓ + c₃`, `v₄ = b·ℓ + ωθ + c₄`, summed via
`slotCost` and minimized over the free `p, c₂, c₃, c₄ ∈ F₄`. -/

/-- The labeling `ℓ` over the four slots `(e,x,y,xy)`:
`ℓ = (ω²,ω,1,0) = (3,2,1,0)` (`= ellL`, by `ellL_eq`; `ellL_inj` is the
bijectivity used in the pencil lemmas). -/
def ellSlots : List (Fin 4) := [3, 2, 1, 0]

/-- `ωθ` over the four slots: `ω·(1,0,1,0) = (2,0,2,0)` (the wt-24 component-4
offset). -/
def wThetaSlots : List (Fin 4) := [2, 0, 2, 0]

/-- `ellSlots` is genuinely `ℓ = ellL` evaluated over `allS = (e,x,y,xy)`. -/
theorem ellSlots_eq : ellSlots = [ellL (0,0), ellL (1,0), ellL (0,1), ellL (1,1)] := by decide

/-- `wThetaSlots` is genuinely `ωθ = ω·theta` evaluated over `allS`. -/
theorem wThetaSlots_eq :
    wThetaSlots = [fmul 2 (theta (0,0)), fmul 2 (theta (1,0)),
                   fmul 2 (theta (0,1)), fmul 2 (theta (1,1))] := by decide

/-- **The standard form `S(a,b)`** (Def 26): the `v₀`-free block cost with
confined line `⟨ℓ⟩`, spine directions `v₃ = a·ℓ + c₃`, `v₄ = b·ℓ + ωθ + c₄`,
minimized over the free constants `p, c₂, c₃, c₄ ∈ F₄`. -/
def Sab (a b : Fin 4) : Nat :=
  (([0,1,2,3] : List (Fin 4)).flatMap fun p => ([0,1,2,3] : List (Fin 4)).flatMap fun c2 =>
   ([0,1,2,3] : List (Fin 4)).flatMap fun c3 => ([0,1,2,3] : List (Fin 4)).map fun c4 =>
    (List.zip ellSlots wThetaSlots).foldr (fun pr acc =>
      acc + slotCost (fadd (fmul p pr.1) c2) (fadd (fmul a pr.1) c3)
                     (fadd (fadd (fmul b pr.1) pr.2) c4)) 0
  ).foldr min 999

/-- **Proposition 29** (the standard-form walk): `S(a,b) ≥ 6` for all
`(a,b) ∈ F₄²`. Hence every weight-24 spine cell has linked block cost
`≥ 6 + 6 = 12`. Kernel `decide` over the 16 pairs — **axiom-clean** (`propext`
only). `+kernel` skips the elaborator evaluation; the packed-`Nat` tables keep
the walk cheap. -/
theorem Sab_ge_6 : ∀ a b : Fin 4, 6 ≤ Sab a b := by decide +kernel

end Quantum.Stabilizer.Homological.BB.LightStab
